# Translations for spanish
#
# Copyright (c) 2012 Virtual Cable S.L.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
#    * Redistributions of source code must retain the above copyright notice,
#      this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright notice,
#      this list of conditions and the following disclaimer in the documentation
#      and/or other materials provided with the distribution.
#    * Neither the name of Virtual Cable S.L. nor the names of its contributors
#      may be used to endorse or promote products derived from this software
#      without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Adolfo Gómez <dkmaster at dkmon dot com>, 2012.
msgid ""
msgstr ""
"Project-Id-Version: \n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2012-11-28 10:17+0100\n"
"PO-Revision-Date: 2012-11-28 10:28+0100\n"
"Last-Translator: \n"
"Language-Team: Spanish <kde-i18n-doc@kde.org>\n"
"Language: es\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"X-Generator: Lokalize 1.4\n"

#: auths/ActiveDirectory_enterprise/Authenticator.py:29
#: auths/EDirectory_enterprise/Authenticator.py:60
#: auths/RegexLdap/Authenticator.py:49 auths/SimpleLDAP/Authenticator.py:49
#: services/OVirt/OVirtProvider.py:91
#: services/Vmware_enterprise/ServiceProviderVC.py:28
msgid "Host"
msgstr "Servidor "

#: auths/ActiveDirectory_enterprise/Authenticator.py:29
#: auths/EDirectory_enterprise/Authenticator.py:60
#: auths/RegexLdap/Authenticator.py:49 auths/SimpleLDAP/Authenticator.py:49
#: services/Vmware_enterprise/ServiceProviderVC.py:28
msgid "VMWare VC Server IP or Hostname"
msgstr "IP o nombre DNS del servidor VMWare VC"

#: auths/ActiveDirectory_enterprise/Authenticator.py:30
#: auths/EDirectory_enterprise/Authenticator.py:62
#: auths/RegexLdap/Authenticator.py:51 auths/SimpleLDAP/Authenticator.py:51
msgid "Use SSL"
msgstr "Usar SSL"

#: auths/ActiveDirectory_enterprise/Authenticator.py:30
msgid "If checked, will use a ssl connection to Active Directory"
msgstr "Si está activada, utilizará una conexión ssl con Active Directory"

#: auths/ActiveDirectory_enterprise/Authenticator.py:31
#: auths/RegexLdap/Authenticator.py:52 auths/SimpleLDAP/Authenticator.py:52
msgid "Ldap User"
msgstr "Usuario LDAP"

#: auths/ActiveDirectory_enterprise/Authenticator.py:31
msgid ""
"Username with read privileges on the base selected (use USER@DOMAIN.DOM form "
"for this)"
msgstr ""
"Usuario con derechos de lectura en la base seleccionada (utilice la forma "
"USUARIO@DOMINIO.DOM para este elemento)"

#: auths/ActiveDirectory_enterprise/Authenticator.py:32
#: auths/ActiveDirectory_enterprise/Authenticator.py:50
#: auths/EDirectory_enterprise/Authenticator.py:64
#: auths/RegexLdap/Authenticator.py:53 auths/RegexLdap/Authenticator.py:76
#: auths/SimpleLDAP/Authenticator.py:53 auths/SimpleLDAP/Authenticator.py:77
#: osmanagers/WindowsOsManager/WinDomainOsManager.py:31
#: osmanagers/WindowsOsManager/WinRandomPassOsManager.py:30
#: services/OVirt/OVirtProvider.py:93
#: services/Vmware_enterprise/ServiceProviderVC.py:31
#: transports/NX/NXTransport.py:62 transports/RDP/RDPTransport.py:38
#: transports/RDP/TSRDPTransport.py:42
#: transports/RGS-enterprise/RGSTransport.py:43
#: transports/RGS-enterprise/TRGSTransport.py:48
#: transports/TSNX/TSNXTransport.py:67 web/forms/LoginForm.py:58
msgid "Password"
msgstr "Contraseña"

#: auths/ActiveDirectory_enterprise/Authenticator.py:32
#: auths/EDirectory_enterprise/Authenticator.py:64
#: auths/RegexLdap/Authenticator.py:53 auths/SimpleLDAP/Authenticator.py:53
msgid "Password of the ldap user"
msgstr "Contraseña del usuario del ldap"

#: auths/ActiveDirectory_enterprise/Authenticator.py:33
#: auths/EDirectory_enterprise/Authenticator.py:65
#: auths/RegexLdap/Authenticator.py:54 auths/SimpleLDAP/Authenticator.py:54
#: services/OVirt/OVirtProvider.py:94
#: services/Vmware_enterprise/ServiceProviderVC.py:32
msgid "Timeout"
msgstr "Espera "

#: auths/ActiveDirectory_enterprise/Authenticator.py:33
#: auths/EDirectory_enterprise/Authenticator.py:65
#: auths/RegexLdap/Authenticator.py:54 auths/SimpleLDAP/Authenticator.py:54
msgid "Timeout in seconds of connection to LDAP"
msgstr "Tiempo de espera en segundos"

#: auths/ActiveDirectory_enterprise/Authenticator.py:35
msgid "Active Directory Authenticator"
msgstr "Autenticador Active Directory"

#: auths/ActiveDirectory_enterprise/Authenticator.py:37
msgid "Authenticate against Active Directory"
msgstr "Autenticador contra Active Directory"

#: auths/ActiveDirectory_enterprise/Authenticator.py:46
#: auths/EDirectory_enterprise/Authenticator.py:77
#: auths/RegexLdap/Authenticator.py:72 auths/SimpleLDAP/Authenticator.py:73
#: services/OVirt/OVirtProvider.py:92
#: services/Vmware_enterprise/ServiceProviderVC.py:30
#: transports/NX/NXTransport.py:61 transports/RDP/RDPTransport.py:37
#: transports/RDP/TSRDPTransport.py:41
#: transports/RGS-enterprise/RGSTransport.py:42
#: transports/RGS-enterprise/TRGSTransport.py:47
#: transports/TSNX/TSNXTransport.py:66 web/forms/LoginForm.py:57
msgid "Username"
msgstr "Usuario"

#: auths/ActiveDirectory_enterprise/Authenticator.py:48
#: auths/EDirectory_enterprise/Authenticator.py:79
#: auths/RegexLdap/Authenticator.py:74 auths/SAML_enterprise/SAML.py:113
#: auths/SimpleLDAP/Authenticator.py:75
msgid "Group"
msgstr "Grupo"

#: auths/ActiveDirectory_enterprise/Authenticator.py:61
#: auths/ActiveDirectory_enterprise/Authenticator.py:395
msgid "Must specify the username in the form USERNAME@DOMAIN.DOM"
msgstr ""
"Debe especificar el nombre de usuario en la forma NOMBREUSUARIO@DOMINIO.DOM"

#: auths/ActiveDirectory_enterprise/Authenticator.py:127
#: auths/EDirectory_enterprise/Authenticator.py:123
#: auths/RegexLdap/Authenticator.py:159 auths/SimpleLDAP/Authenticator.py:158
msgid "Ldap connection error: "
msgstr "Error de conexión al ldap: "

#: auths/ActiveDirectory_enterprise/Authenticator.py:299
#: auths/ActiveDirectory_enterprise/Authenticator.py:345
#: auths/EDirectory_enterprise/Authenticator.py:243
#: auths/EDirectory_enterprise/Authenticator.py:286
#: auths/RegexLdap/Authenticator.py:249 auths/RegexLdap/Authenticator.py:292
#: auths/SimpleLDAP/Authenticator.py:269 auths/SimpleLDAP/Authenticator.py:313
msgid "Username not found"
msgstr "Nombre de usuario no hallado"

#: auths/ActiveDirectory_enterprise/Authenticator.py:332
#: auths/SimpleLDAP/Authenticator.py:302
msgid "Group not found"
msgstr "Grupo no hallado"

#: auths/ActiveDirectory_enterprise/Authenticator.py:364
#: auths/ActiveDirectory_enterprise/Authenticator.py:381
#: auths/EDirectory_enterprise/Authenticator.py:303
#: auths/RegexLdap/Authenticator.py:309 auths/SimpleLDAP/Authenticator.py:328
#: auths/SimpleLDAP/Authenticator.py:342
msgid "Too many results, be more specific"
msgstr "Demasiados resultados, sea más específico"

#: auths/ActiveDirectory_enterprise/Authenticator.py:404
msgid "Domain seems to be incorrect, please check it"
msgstr "El dominio parece ser incorrecto, por favor, compruebelo"

#: auths/ActiveDirectory_enterprise/Authenticator.py:409
msgid "Ldap does not seem an Active Directory (do not have user objects)"
msgstr ""
"El ldap indicado no parece un Active Directory (no tiene objetos de usuario)"

#: auths/ActiveDirectory_enterprise/Authenticator.py:417
msgid "Ldap does not seem an Active Directory (no not have group objects)"
msgstr ""
"El ldap indicado no parece un Active Directory (no no tienen objetos de "
"grupo)"

#: auths/ActiveDirectory_enterprise/Authenticator.py:425
msgid ""
"Ldap does not seem an Active Directory (do not have any user nor groups)"
msgstr ""
"El ldap indicado no parece un Active Directory (no tiene ningún usuario ni "
"grupo)"

#: auths/ActiveDirectory_enterprise/Authenticator.py:430
#: auths/EDirectory_enterprise/Authenticator.py:358
#: auths/RegexLdap/Authenticator.py:384 auths/SimpleLDAP/Authenticator.py:423
msgid "Connection params seem correct, test was succesfully executed"
msgstr ""
"Los parámetros de conexión parecen correctos, la prueba fue ejecutado con "
"exito"

#: auths/EDirectory_enterprise/Authenticator.py:61
#: auths/RegexLdap/Authenticator.py:50 auths/SimpleLDAP/Authenticator.py:50
#: services/Vmware_enterprise/ServiceProviderVC.py:29
msgid "Port"
msgstr "Puerto"

#: auths/EDirectory_enterprise/Authenticator.py:61
#: auths/RegexLdap/Authenticator.py:50 auths/SimpleLDAP/Authenticator.py:50
msgid "Ldap port (389 for non ssl, 636 for ssl normally"
msgstr "Puerto LDAP (389 para no SSL, 636 para ssl normalmente)"

#: auths/EDirectory_enterprise/Authenticator.py:62
#: auths/RegexLdap/Authenticator.py:51 auths/SimpleLDAP/Authenticator.py:51
msgid ""
"If checked, will use a ssl connection to ldap (if port is 389, will use in "
"fact port 636)"
msgstr ""
"Si está activada, utilizará una conexión ssl con ldap (si el puerto es 389, "
"utilizará de hecho el Puerto 636)"

#: auths/EDirectory_enterprise/Authenticator.py:63
msgid "Admin user"
msgstr "Usuario Administrador"

#: auths/EDirectory_enterprise/Authenticator.py:63
msgid "Username with read privileges on the eDirectory"
msgstr "Usuario con privilegios de lectura sobre eDirectory"

#: auths/EDirectory_enterprise/Authenticator.py:67
msgid "eDirectory Authenticator"
msgstr "Autenticador eDirectory"

#: auths/EDirectory_enterprise/Authenticator.py:69
msgid "Authenticate against eDirectory"
msgstr "Autenticador contra eDirectory"

#: auths/EDirectory_enterprise/Authenticator.py:323
#: auths/RegexLdap/Authenticator.py:329 auths/SimpleLDAP/Authenticator.py:363
msgid "Ldap search base is incorrect"
msgstr "La base de búsqueda ldap es incorrecta"

#: auths/EDirectory_enterprise/Authenticator.py:328
#: auths/RegexLdap/Authenticator.py:334 auths/SimpleLDAP/Authenticator.py:368
msgid "Ldap user class seems to be incorrect (no user found by that class)"
msgstr ""
"La clase de usuario de LDAP parece ser incorrecta (ningún usuario encontrado "
"por esa clase)"

#: auths/EDirectory_enterprise/Authenticator.py:336
#: auths/RegexLdap/Authenticator.py:350 auths/SimpleLDAP/Authenticator.py:384
msgid ""
"Ldap user id attribute seems to be incorrect (no user found by that "
"attribute)"
msgstr ""
"El atributo de id de usuario de ldap parece ser incorrecto (ningún usuario "
"encontrado por atributo)"

#: auths/EDirectory_enterprise/Authenticator.py:344
msgid "Expected group attribute "
msgstr "Atributo de grupo esperado "

#: auths/EDirectory_enterprise/Authenticator.py:353
msgid ""
"Ldap user class or user id attr is probably wrong (Ldap is an eDirectory?)"
msgstr ""
"El atributo del id de usuario o la clase de usuario LDAP son probablemente "
"incorrectos(¿el LDAP indicado es realmente un eDirectory?)"

#: auths/IP/Authenticator.py:45 auths/IP/Authenticator.py:47
msgid "IP Authenticator"
msgstr "Autenticador por IP"

#: auths/IP/Authenticator.py:51
msgid "IP"
msgstr "IP "

#: auths/IP/Authenticator.py:52
msgid "IP Range"
msgstr "Intervalo IP"

#: auths/IP/Authenticator.py:99 auths/InternalDB/Authenticator.py:102
msgid "All seems fine in the authenticator."
msgstr "Parace que todo funciona correctamente en el autenticador. "

#: auths/InternalDB/Authenticator.py:46
msgid "Internal Database"
msgstr "Base de datos interna"

#: auths/InternalDB/Authenticator.py:48
msgid "Internal dabasase authenticator. Doesn't uses external sources"
msgstr "Dabasase interna autenticador. No utiliza fuentes externas"

#: auths/InternalDB/Authenticator.py:99
msgid "Internal structures seems ok"
msgstr "Las estructuras internas parecen correctas"

#: auths/RegexLdap/Authenticator.py:52 auths/SimpleLDAP/Authenticator.py:52
msgid "Username with read privileges on the base selected"
msgstr "Usuario con privilegios de lectura en la base elegida"

#: auths/RegexLdap/Authenticator.py:55 auths/SimpleLDAP/Authenticator.py:55
msgid "Base"
msgstr "Base"

#: auths/RegexLdap/Authenticator.py:55 auths/SimpleLDAP/Authenticator.py:55
msgid "Common search base (used for \"users\" and \"groups\""
msgstr "Base de búsqueda común (utilizado para \"los usuarios\" y \"grupos\""

#: auths/RegexLdap/Authenticator.py:56 auths/SimpleLDAP/Authenticator.py:56
msgid "User class"
msgstr "Clase de usuario"

#: auths/RegexLdap/Authenticator.py:56 auths/SimpleLDAP/Authenticator.py:56
msgid "Class for LDAP users (normally posixAccount)"
msgstr "Clase para los usuarios de LDAP (normalmente posixAccount)"

#: auths/RegexLdap/Authenticator.py:57 auths/SimpleLDAP/Authenticator.py:57
msgid "User Id Attr"
msgstr "Attr. de Id de usuario"

#: auths/RegexLdap/Authenticator.py:57 auths/SimpleLDAP/Authenticator.py:57
msgid "Attribute that contains the user id"
msgstr "Atributo que contiene el identificador de usuario"

#: auths/RegexLdap/Authenticator.py:58 auths/SimpleLDAP/Authenticator.py:58
msgid "User Name Attr"
msgstr "Attr. de nombre usu."

#: auths/RegexLdap/Authenticator.py:58 auths/SimpleLDAP/Authenticator.py:58
msgid "Attributes that contains the user name (list of comma separated values)"
msgstr ""
"Atributos que contienen el nombre de usuario (lista de valores separados por "
"comas)"

#: auths/RegexLdap/Authenticator.py:59
msgid "Group Name Attr"
msgstr "Atr. de nombre de Grupo"

#: auths/RegexLdap/Authenticator.py:59
msgid "Attribute that contains the group name"
msgstr "Atributo que contiene el nombre del grupo"

#: auths/RegexLdap/Authenticator.py:60
msgid "Regular Exp. for groups"
msgstr "EXP. regular para grupos"

#: auths/RegexLdap/Authenticator.py:60
msgid "Regular Expression to extract the group name"
msgstr "Expresión regular para extraer el nombre del grupo"

#: auths/RegexLdap/Authenticator.py:62
msgid "Regex LDAP Authenticator"
msgstr "Autenticador Regex LDAP"

#: auths/RegexLdap/Authenticator.py:64
msgid "Regular Expressions LDAP authenticator"
msgstr "Autenticador LDAP de expresiones regulares"

#: auths/RegexLdap/Authenticator.py:96
msgid "Invalid regular expression"
msgstr "Expresión regular inválida"

#: auths/RegexLdap/Authenticator.py:342 auths/SimpleLDAP/Authenticator.py:376
msgid "Ldap group class seems to be incorrect (no group found by that class)"
msgstr ""
"La clase de grupo LDAP parece ser incorrecta (ningún grupo encontrado por "
"esa clase)"

#: auths/RegexLdap/Authenticator.py:360 auths/SimpleLDAP/Authenticator.py:392
msgid ""
"Ldap group id attribute seems to be incorrect (no group found by that "
"attribute)"
msgstr ""
"Atributo de id de grupo ldap parece ser incorrecto (ningún grupo encontrado "
"por atributo)"

#: auths/RegexLdap/Authenticator.py:369 auths/SimpleLDAP/Authenticator.py:401
msgid ""
"Ldap user class or user id attr is probably wrong (can't find any user with "
"both conditions)"
msgstr ""
"El atributo del id de usuario o la clase de usuario LDAP son probablemente "
"incorrectos(no se puede encontrar ningún usuario con ambas condiciones)"

#: auths/SAML_enterprise/SAML.py:79
msgid "SAML Authenticator"
msgstr "Autenticador SAML"

#: auths/SAML_enterprise/SAML.py:91
msgid "SAML (v2.0) Authenticator"
msgstr "Autenticador SAML (versión 2.0)"

#: auths/SAML_enterprise/SAML.py:110 templates/uds/internal_page.html:28
msgid "User"
msgstr "Usuario"

#: auths/SAML_enterprise/SAML.py:119
msgid "Private key"
msgstr "Clave privada"

#: auths/SAML_enterprise/SAML.py:120
msgid ""
"Private key used for sign and encription, as generated in base 64 from "
"openssl"
msgstr ""
"Clave privada usada para la firma y la encriptación, en el formato que se "
"genera en base64 por openssl"

#: auths/SAML_enterprise/SAML.py:121
msgid "Certificate"
msgstr "Certificado"

#: auths/SAML_enterprise/SAML.py:122
msgid "Server certificate (public), , as generated in base 64 from openssl"
msgstr ""
"Certificado del servidor (público). Como se genera en base 62 desde openssl"

#: auths/SAML_enterprise/SAML.py:123
msgid "IDP Metadata"
msgstr "Metadata del IDP"

#: auths/SAML_enterprise/SAML.py:124
msgid ""
"You can enter here the URL or the IDP metadata or the metadata itself (xml)"
msgstr ""
"Puede insertar aqui la URL de los metadatos del IDP, o bien los metadatos "
"mismos (en xml) "

#: auths/SAML_enterprise/SAML.py:126
msgid "Entity ID"
msgstr "Entity ID"

#: auths/SAML_enterprise/SAML.py:127
msgid "ID of the SP. If left blank, this will be autogenerated from server URL"
msgstr ""
"ID del SP. Si se deja en blanco, será generado automáticamente usando el "
"nombre de servidor utilizado para hacer login en la administración."

#: auths/SAML_enterprise/SAML.py:129
msgid "User name attrs"
msgstr "Attrs. de nombre usu."

#: auths/SAML_enterprise/SAML.py:130
msgid "Fields from where to extract user name"
msgstr "Expresión regular para extraer el nombre de usuario"

#: auths/SAML_enterprise/SAML.py:132
msgid "Group name attrs"
msgstr "Atrs. de nombres de Grupos"

#: auths/SAML_enterprise/SAML.py:133
#, fuzzy
msgid "Fields from where to extract the groups"
msgstr "Expresión regular para extraer el nombre del grupo"

#: auths/SAML_enterprise/SAML.py:135
msgid "Real name attrs"
msgstr "Attr. de nombre real"

#: auths/SAML_enterprise/SAML.py:136
msgid "Fields from where to extract the real name"
msgstr "Expresión regular para extraer el nombre real del usuario"

#: auths/SAML_enterprise/SAML.py:159
msgid ""
"Server certificate should be a valid PEM (PEM certificates starts with -----"
"BEGIN CERTIFICATE-----)"
msgstr ""
"El certificado del servidor debe estarn en formato PEM (Los certificados en "
"formato PEM empiezan por ---BEGIN CERTIFICATE---)"

#: auths/SAML_enterprise/SAML.py:164
msgid "Invalid server certificate. "
msgstr "Certificado de servidor inválido"

#: auths/SAML_enterprise/SAML.py:167
msgid ""
"Private key should be a valid PEM (PEM private keys starts with -----BEGIN "
"RSA PRIVATE KEY-----"
msgstr ""
"La clave privada debe estar en formato PEM (los claves privadas en formato "
"PEM comienzan por ---BEGIN RSA PRIVATE KEY---)"

#: auths/SAML_enterprise/SAML.py:196
msgid "Can't fetch url {0}: {1}"
msgstr "No puedo obtener la url {0}: {1}"

#: auths/SAML_enterprise/SAML.py:207
msgid " (obtained from URL)"
msgstr "(obtenido de la URL)"

#: auths/SAML_enterprise/SAML.py:208
msgid "XML do not seems valid for IDP Metadata "
msgstr "El XML no parece ser válido para Metdatos de un IDP"

#: auths/SAML_enterprise/SAML.py:224
msgid "Can't access idp metadata"
msgstr "No se puee acceder a los metadatos del IDP"

#: auths/SimpleLDAP/Authenticator.py:59
msgid "Group class"
msgstr "Clase de grupo"

#: auths/SimpleLDAP/Authenticator.py:59
msgid "Class for LDAP groups (normally poxisGroup)"
msgstr "Clase de grupos LDAP (normalmente poxisGroup)"

#: auths/SimpleLDAP/Authenticator.py:60
msgid "Group Id Attr"
msgstr "Atr. id de Grupo"

#: auths/SimpleLDAP/Authenticator.py:60
msgid "Attribute that contains the group id"
msgstr "Atributo que contiene el id de grupo"

#: auths/SimpleLDAP/Authenticator.py:61
msgid "Group membership attr"
msgstr "Atr. de pertenencia de grupo"

#: auths/SimpleLDAP/Authenticator.py:61
msgid "Attribute of the group that contains the users belonging to it"
msgstr "Atributo del grupo que contiene los usuarios pertenecientes al mismo"

#: auths/SimpleLDAP/Authenticator.py:63
msgid "SimpleLDAP Authenticator"
msgstr "Autenticador LDAP Simple"

#: auths/SimpleLDAP/Authenticator.py:65
msgid "Simple LDAP authenticator"
msgstr "Autenticador LDAP Simple"

#: auths/SimpleLDAP/Authenticator.py:410
msgid ""
"Ldap group class or group id attr is probably wrong (can't find any group "
"with both conditions)"
msgstr ""
"El atributo del identificador de clase o grupo de grupo LDAP son "
"probablemente incorrectos (no se encuentra ningún grupo con ambas "
"condiciones)"

#: auths/SimpleLDAP/Authenticator.py:417
msgid "Can't locate any group with the membership attribute specified"
msgstr ""
"No se puede localizar algún grupo con el atributo de pertenencia especificado"

#: core/BaseModule.py:196
msgid "No connection checking method is implemented."
msgstr "No se ha implementado ningun metodo de comprobación de conexión"

#: core/BaseModule.py:253
msgid "No check method provided."
msgstr "No se ha implementado ningún método de verificación."

#: core/managers/PublicationManager.py:152
msgid ""
"Already publishing. Wait for previous publication to finish and try again"
msgstr ""
"Ya hay una publicación en curso. Espere a la finalización de esta o "
"cancelela e intentelo de nuevo."

#: core/managers/PublicationManager.py:165
msgid "Can't cancel non running publication"
msgstr "No se puede cancelar una publicación que no está activa"

#: core/managers/PublicationManager.py:183
msgid "Can't unpublish non usable publication"
msgstr "No se puede despublicar una publicación no activa"

#: core/managers/PublicationManager.py:186
msgid "Can't unpublish publications with services in process"
msgstr "No se puede despublicar con servicios en proceso"

#: core/managers/UserPrefsManager.py:254
msgid "Screen Size"
msgstr "Tamaño de pantalla"

#: core/managers/UserPrefsManager.py:258
msgid "Full Screen"
msgstr "Pantalla completa"

#: core/managers/UserPrefsManager.py:261
msgid "Screen colors"
msgstr "Colores de pantalla"

#: core/managers/UserPrefsManager.py:262
msgid "8 bits"
msgstr "8 bits"

#: core/managers/UserPrefsManager.py:263
msgid "16 bits"
msgstr "16 bits"

#: core/managers/UserPrefsManager.py:264
msgid "24 bits"
msgstr "24 bits"

#: core/managers/UserPrefsManager.py:265
msgid "32 bits"
msgstr "32 bits"

#: core/managers/UserServiceManager.py:303
msgid "Can't cancel non running operation"
msgstr "No se puede cancelar una operación que no está en curso"

#: core/managers/UserServiceManager.py:322
msgid "Can't remove a non active element"
msgstr "No se puede eliminar un elemento que no está activo"

#: core/managers/UserServiceManager.py:335
msgid "Can't remove nor cancel {0} cause its states doesn't allows it"
msgstr "No se puede eliminar o cancelar {0} porque sus estados no lo permiten"

#: core/osmanagers/BaseOsManager.py:49
msgid "Base OS Manager"
msgstr "Gestor de OS Base"

#: core/osmanagers/BaseOsManager.py:51
msgid "Base Manager"
msgstr "Gestor Base"

#: core/transports/BaseTransport.py:113
msgid "Transport empty"
msgstr "Transporte Vacio"

#: core/util/State.py:59
msgid "Active"
msgstr "Activo"

#: core/util/State.py:59
msgid "Inactive"
msgstr "Inactivo"

#: core/util/State.py:59
msgid "Blocked"
msgstr "Bloqueado"

#: core/util/State.py:59
msgid "Waiting publication"
msgstr "En espera de publicación"

#: core/util/State.py:60
msgid "In preparation"
msgstr "En preparación"

#: core/util/State.py:60
msgid "Valid"
msgstr "Valido"

#: core/util/State.py:61
msgid "Waiting for removal"
msgstr "Esperando eliminación"

#: core/util/State.py:61
msgid "Removing"
msgstr "Eliminandose"

#: core/util/State.py:61
msgid "Removed"
msgstr "Eliminado "

#: core/util/State.py:61
msgid "Canceled"
msgstr "Cancelado"

#: core/util/State.py:62
msgid "Canceling"
msgstr "Cancelando"

#: core/util/State.py:62 templates/uds/error.html:6
#: templates/uds/error.html.py:11
msgid "Error"
msgstr "Error"

#: core/util/State.py:62
msgid "Running"
msgstr "En ejecución"

#: core/util/State.py:62
msgid "Finished"
msgstr "Finalizado"

#: core/util/State.py:62
msgid "Waiting execution"
msgstr "En espera de ejecución"

#: osmanagers/LinuxOsManager/LinuxOsManager.py:45
msgid "Linux OS Manager"
msgstr "Gestor de S.O. Linux"

#: osmanagers/LinuxOsManager/LinuxOsManager.py:47
msgid ""
"Os Manager to control linux virtual machines (basically renames machine and "
"notify state)"
msgstr ""
"Gestor de s.o. para controlar maquinas virtuales con linux (basicamente "
"renombra las máquinas y notifica los estados)"

#: osmanagers/LinuxOsManager/LinuxOsManager.py:50
#: osmanagers/WindowsOsManager/WindowsOsManager.py:41
msgid "On Logout"
msgstr "Al salir"

#: osmanagers/LinuxOsManager/LinuxOsManager.py:50
#: osmanagers/WindowsOsManager/WindowsOsManager.py:41
msgid "What to do when user logout from service"
msgstr "Que acción realizar cuando el usuario abandone el servicio"

#: osmanagers/LinuxOsManager/LinuxOsManager.py:51
#: osmanagers/WindowsOsManager/WindowsOsManager.py:42
msgid "Keep service assigned"
msgstr "Mantener el servicio asignado"

#: osmanagers/LinuxOsManager/LinuxOsManager.py:52
#: osmanagers/WindowsOsManager/WindowsOsManager.py:43
msgid "Remove service"
msgstr "Eliminar servicio"

#: osmanagers/LinuxOsManager/__init__.py:43
msgid "UDS Actor for linux machines <b>(Requires python 2.6 or greater)"
msgstr "Actor para las máquinas Linux <b>(Precisa python 2.6 o mayor)</b>"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:23
msgid "Windows Domain OS Manager"
msgstr "Gestor para Windows con dominio"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:25
msgid ""
"Os Manager to control windows machines with domain. (Basically renames "
"machine)"
msgstr "Gestor de s.o. para controlar maquinas windows con dominio."

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:29
#: transports/RDP/RDPTransport.py:39 transports/RDP/TSRDPTransport.py:43
#: transports/RGS-enterprise/RGSTransport.py:44
#: transports/RGS-enterprise/TRGSTransport.py:49
msgid "Domain"
msgstr "Dominio"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:29
msgid "Domain to join machines to (better use dns form of domain)"
msgstr ""
"Dominio al que unir las máquinas (es preferible utilizar la forma DNS del "
"dominio)"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:30
#: osmanagers/WindowsOsManager/WinRandomPassOsManager.py:29
msgid "Account"
msgstr "Cuenta"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:30
msgid "Account with rights to add machines to domain"
msgstr "Cuenta con derecho para añadir máquinas al dominio"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:31
msgid "Password of the account"
msgstr "Contraseña de la cuenta"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:32
msgid "OU"
msgstr "OU"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:32
msgid ""
"Organizational unit where to add machines in domain (check it before using "
"it)"
msgstr ""
"Unidad organizativa donde crear las máquinas del dominio (compruebelo antes "
"de utilizarlo)"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:40
msgid "Must provide a domain!!!"
msgstr "Debe indicar un dominio!!!"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:42
msgid "Must provide an account to add machines to domain!!!"
msgstr "Debe indicar una cuenta para añadir máquinas al dominio!!!"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:44
#: osmanagers/WindowsOsManager/WinRandomPassOsManager.py:41
msgid "Must provide a password for the account!!!"
msgstr "Debe indicar una contraseña para la cuenta!!!"

#: osmanagers/WindowsOsManager/WinRandomPassOsManager.py:23
msgid "Windows Random Password OS Manager"
msgstr "Gestor para windows con contraseña aleatoria"

#: osmanagers/WindowsOsManager/WinRandomPassOsManager.py:25
msgid ""
"Os Manager to control windows machines, with user password set randomly."
msgstr ""
"Gestor de s.o. para controlar maquinas windows con contraseñas aleatorias"

#: osmanagers/WindowsOsManager/WinRandomPassOsManager.py:29
msgid "User account to change password"
msgstr "Cuenta de usuario a la que cambiar el password"

#: osmanagers/WindowsOsManager/WinRandomPassOsManager.py:30
msgid "Current (template) password of the user account"
msgstr "Contraseña (la fijada en la plantilla) del usuario"

#: osmanagers/WindowsOsManager/WinRandomPassOsManager.py:39
msgid "Must provide an user account!!!"
msgstr "Debe indicar una cuenta de usuario!!!"

#: osmanagers/WindowsOsManager/WindowsOsManager.py:36
msgid "Windows Basic OS Manager"
msgstr "Gestor de SO Windows Básico"

#: osmanagers/WindowsOsManager/WindowsOsManager.py:38
msgid ""
"Os Manager to control windows machines without domain. (Basically renames "
"machine)"
msgstr ""
"Gestor de SO para controlar máquinas windows sin dominio. (Basicamente, "
"renombra las máquinas)"

#: osmanagers/WindowsOsManager/WindowsOsManager.py:52
msgid "Length must be numeric!!"
msgstr "La longitud debe ser numerica!!!"

#: osmanagers/WindowsOsManager/WindowsOsManager.py:54
msgid "Length must be betwen 1 and six"
msgstr "La longitud debe estar entre 1 y seis"

#: osmanagers/WindowsOsManager/__init__.py:25
msgid ""
"UDS Actor for windows machines <b>(Important!! Requires .net framework 3.5 "
"sp1)</b>"
msgstr ""
"Actor para las máquinas Windows <b>(Importante!!! Requiere tener .net "
"framework 3.5 sp1)</b>"

#: services/OVirt/OVirtLinkedService.py:56
msgid "oVirt Linked Clone"
msgstr "Servicio basado en oVirt Clones COW"

#: services/OVirt/OVirtLinkedService.py:60
msgid "oVirt Services based on templates and COW"
msgstr "Servicioes oVirt basadoes en plantillas y COW"

#: services/OVirt/OVirtLinkedService.py:77
#: services/Vmware_enterprise/VCLinkedCloneService.py:70
msgid "Number of desired machines to keep running waiting for a user"
msgstr "Número de máquinas a manatener en ejecución esperando a un usuario"

#: services/OVirt/OVirtLinkedService.py:83
#: services/Vmware_enterprise/VCLinkedCloneService.py:72
msgid "Number of desired machines to keep suspended waiting for use"
msgstr "Número de maquinas a mantener suspendidas esperando asignación"

#: services/OVirt/OVirtLinkedService.py:99
#: services/Vmware_enterprise/VCLinkedCloneService.py:48
msgid "Base Machine"
msgstr "Máquina de base"

#: services/OVirt/OVirtLinkedService.py:99
msgid "Service base machine"
msgstr "Máquina de base para el servicio"

#: services/OVirt/OVirtLinkedService.py:100
msgid "Cluster"
msgstr "Cluster"

#: services/OVirt/OVirtLinkedService.py:106
msgid "Cluster to contain services"
msgstr "Cluster que contrendrá los servicios"

#: services/OVirt/OVirtLinkedService.py:109
msgid "Datastore Domain"
msgstr "Almacenamiento"

#: services/OVirt/OVirtLinkedService.py:110
msgid "Datastore domain where to publish and put incrementals"
msgstr "Almacenamiento donde colocar los incrementales y las publicaciones"

#: services/OVirt/OVirtLinkedService.py:112
#: services/Vmware_enterprise/VCLinkedCloneService.py:49
msgid "Memory (Mb)"
msgstr "Memoria (Mb)"

#: services/OVirt/OVirtLinkedService.py:113
msgid "Memory assigned to machines"
msgstr "Memoria asignada a las máquinas"

#: services/OVirt/OVirtLinkedService.py:115
msgid "Memory Guaranteed (Mb)"
msgstr "Memoria Garantizada (Mb)"

#: services/OVirt/OVirtLinkedService.py:116
msgid "Physical memory guaranteed to machines"
msgstr "Memoria física garantizada a las máquinas"

#: services/OVirt/OVirtLinkedService.py:118
#: services/Vmware_enterprise/VCLinkedCloneService.py:53
msgid "Machine Names"
msgstr "Nombres de máquinas"

#: services/OVirt/OVirtLinkedService.py:119
#: services/Vmware_enterprise/VCLinkedCloneService.py:54
msgid "Name Length"
msgstr "Longitud del nombre"

#: services/OVirt/OVirtLinkedService.py:120
#: services/Vmware_enterprise/VCLinkedCloneService.py:55
msgid "Length of numeric part for the names of this machines (betwen 3 and 6"
msgstr ""
"Longitud de la parte numérica de los nombres de esta maquinaria (entre 3 y 6"

#: services/OVirt/OVirtLinkedService.py:122
msgid "Display"
msgstr "Pantalla"

#: services/OVirt/OVirtLinkedService.py:123
msgid "Display type (only for administration pourposses)"
msgstr "Tipo de pantalla (solo para la administración)"

#: services/OVirt/OVirtLinkedService.py:143
#: services/Vmware_enterprise/VCLinkedCloneService.py:93
msgid "The length of basename plus length must not be greater than 15"
msgstr "La longitud de basename más longitud no debe ser superior a 15"

#: services/OVirt/OVirtLinkedService.py:145
#: services/Vmware_enterprise/VCLinkedCloneService.py:95
msgid "The machine name can't be only numbers"
msgstr "El nombre del equipo no puede ser sólo números"

#: services/OVirt/OVirtProvider.py:72
msgid "oVirt Platform Provider"
msgstr "Proveedor para la plataforma oVirt"

#: services/OVirt/OVirtProvider.py:76
msgid "oVirt platform service provider"
msgstr "Proveedor de servicios para la plataforma oVirt"

#: services/OVirt/OVirtProvider.py:91
msgid "oVirt Server IP or Hostname"
msgstr "IP o nombre DNS del servidor oVirt"

#: services/OVirt/OVirtProvider.py:92
msgid "User with valid privileges on oVirt, (use \"user@domain\" form)"
msgstr "Usuario con privilegios en oVirt (use la forma \"user@domain\")"

#: services/OVirt/OVirtProvider.py:93
msgid "Password of the user of oVirt"
msgstr "Contraseña del usuario de oVirt"

#: services/OVirt/OVirtProvider.py:94
#: services/Vmware_enterprise/ServiceProviderVC.py:32
msgid "Timeout in seconds of connection to VC"
msgstr "Timeout en segundos"

#: services/OVirt/OVirtProvider.py:95
#: services/Vmware_enterprise/ServiceProviderVC.py:33
msgid "Macs range"
msgstr "Rango de Macs"

#: services/OVirt/OVirtProvider.py:96
#: services/Vmware_enterprise/ServiceProviderVC.py:34
msgid "Range of valids macs for created machines"
msgstr "Rango válido de macs para las máquinas creadas"

#: services/OVirt/OVirtProvider.py:395
msgid "Connection test successful"
msgstr "Test de conexión correcto"

#: services/OVirt/OVirtProvider.py:396
#: services/Vmware_enterprise/ServiceProviderVC.py:120
msgid "Connection failed. Check connection params"
msgstr "La conexión ha fallado. Compruebe los parámetros."

#: services/OVirt/OVirtPublication.py:85
msgid "UDS pub for {0} at {1}"
msgstr "Publicación de UDS para {0} en {1}"

#: services/PhysicalMachines/IPMachineDeployed.py:57
msgid "IP "
msgstr "IP "

#: services/PhysicalMachines/IPMachinesService.py:46
msgid "List of IPS"
msgstr "Lista de IPS"

#: services/PhysicalMachines/IPMachinesService.py:49
msgid "Physical machines accesed by ip"
msgstr "Máquinas físicas de acceso por ip"

#: services/PhysicalMachines/IPMachinesService.py:51
msgid "This service provides access to POWERED-ON Machines by ip"
msgstr "Este servicio provee acceso a máquinas ENCENDIDAS por IP"

#: services/Sample/SampleProvider.py:138
msgid "Methuselah is not alive!!! :-)"
msgstr "Matusalén no está vivo!!! :-)"

#: services/Sample/SampleProvider.py:178
msgid "Nothing tested, but all went fine.."
msgstr "Nada probado, pero todo salió bien..."

#: services/Sample/SamplePublication.py:195
msgid "Random integer was 9!!! :-)"
msgstr "Entero aleatorio fue 9!!!!!! :-)"

#: services/Vmware_enterprise/Helpers.py:72
msgid "Local"
msgstr "Local"

#: services/Vmware_enterprise/Helpers.py:74
msgid "Remote"
msgstr "Remoto"

#: services/Vmware_enterprise/PublicationVC.py:37
msgid "Publication"
msgstr "Publicación"

#: services/Vmware_enterprise/PublicationVC.py:38
msgid "UDS Publication for {0} created at {1}"
msgstr "Publicación de UDS para {0} creada el {1}"

#: services/Vmware_enterprise/ServiceProviderVC.py:29
msgid "VMWare VC Server Port (usually 443)"
msgstr "Puerto del servidor VMWare VC (normalmente 443)"

#: services/Vmware_enterprise/ServiceProviderVC.py:30
msgid "User with valid privileges on VC"
msgstr "Usuario con privilegios validos sobre VC"

#: services/Vmware_enterprise/ServiceProviderVC.py:31
msgid "Password of the user of the VC"
msgstr "Contraseña del usuario de VC"

#: services/Vmware_enterprise/ServiceProviderVC.py:39
msgid "VMWare Virtual Center Provider"
msgstr "Proveedor de VMWare Virtual Center"

#: services/Vmware_enterprise/ServiceProviderVC.py:41
msgid "Provides connection to Virtual Center Services"
msgstr "Provee conexión a servicios basados en VMWare Virtual Center"

#: services/Vmware_enterprise/ServiceProviderVC.py:110
msgid "Error testing connection"
msgstr "Error comprobando la conexión"

#: services/Vmware_enterprise/ServiceProviderVC.py:113
msgid "VmwareVC Provider: "
msgstr "Proveedor VmwareVC:"

#: services/Vmware_enterprise/ServiceProviderVC.py:119
msgid "Connection params ok"
msgstr "Parametros de conexión correctos"

#: services/Vmware_enterprise/VCLinkedCloneService.py:28
msgid "Datacenter"
msgstr "Datacenter "

#: services/Vmware_enterprise/VCLinkedCloneService.py:34
msgid "Datacenter containing base machine"
msgstr "Datacenter que contiene la máquina de base"

#: services/Vmware_enterprise/VCLinkedCloneService.py:36
msgid "Network"
msgstr "Red"

#: services/Vmware_enterprise/VCLinkedCloneService.py:37
msgid ""
"If more than 1 interface is found in machine, use one on this network as main"
msgstr ""
"Si hay mas de un interfaz en la máquina virtual, use el que esté en esta red "
"como principal."

#: services/Vmware_enterprise/VCLinkedCloneService.py:38
msgid "Pub. Resource Pool"
msgstr "Pool de despliegue"

#: services/Vmware_enterprise/VCLinkedCloneService.py:38
msgid "Resource Pool where deploy clones"
msgstr "Pool de recursos donde desplegar los clones"

#: services/Vmware_enterprise/VCLinkedCloneService.py:39
msgid "Clones Folder"
msgstr "Carpeta de clones"

#: services/Vmware_enterprise/VCLinkedCloneService.py:39
msgid "Folder where deploy clones"
msgstr "Carpeta donde desplegar los clones"

#: services/Vmware_enterprise/VCLinkedCloneService.py:40
msgid "Resource Pool"
msgstr "Pool de recursos"

#: services/Vmware_enterprise/VCLinkedCloneService.py:46
msgid "Resource Pool containing base machine"
msgstr "Pool de recursos que contiene la máquina de base"

#: services/Vmware_enterprise/VCLinkedCloneService.py:48
msgid "Base machine for this service"
msgstr "Máquina de base para este servicio"

#: services/Vmware_enterprise/VCLinkedCloneService.py:50
msgid "Memory for machines deployed from this service"
msgstr "Memoria para maquinas desplegadas desde este servicio"

#: services/Vmware_enterprise/VCLinkedCloneService.py:51
msgid "Datastores"
msgstr "Almacenamientos"

#: services/Vmware_enterprise/VCLinkedCloneService.py:52
msgid "Datastores where to put incrementals"
msgstr "Almacenamiento donde colocar los incrementales"

#: services/Vmware_enterprise/VCLinkedCloneService.py:53
msgid "Base name for clones from this machine"
msgstr "Nombre base para los clones de la máquina base"

#: services/Vmware_enterprise/VCLinkedCloneService.py:62
msgid "VMWare Linked clone base"
msgstr "Servicio basado en VMWare Linked clones"

#: services/Vmware_enterprise/VCLinkedCloneService.py:64
msgid ""
"This service provides access to Linked Clones machines on a Virtual Center"
msgstr "Este servicio provee acceso a linked clones sobre Virtual Center"

#: templates/404.html:4 templates/404.html.py:7
msgid "Page not found"
msgstr "Página no encontrada"

#: templates/404.html:9
msgid "Sorry, but the requested page could not be found."
msgstr "Lo sentimos, pero no se encontró la página solicitada."

#: templates/uds/base.html:7
msgid "UDS"
msgstr "UDS"

#: templates/uds/detectJava.html:6
msgid "Login redirection"
msgstr "Redireccion del login"

#: templates/uds/detectJava.html:38
msgid "Go to main page"
msgstr "Ir a la página principal"

#: templates/uds/downloads.html:8 templates/uds/snippets/admin_user.html:7
msgid "Downloads"
msgstr "Descargas"

#: templates/uds/downloads.html:11
msgid ""
"This page contains a list of downloadables provided by different modules"
msgstr ""
"Esta página contiene una lista de descargas proporcionadas por diferentes "
"módulos"

#: templates/uds/index.html:51
msgid "Services"
msgstr "Servicios"

#: templates/uds/index.html:70
msgid "Java not found"
msgstr "Java no encontrado"

#: templates/uds/index.html:71
msgid ""
"Java is not available on your browser, and the selected transport needs it."
msgstr ""
"Java no está disponible en el navegador, y el transporte seleccionado "
"precisa de el."

#: templates/uds/index.html:72
msgid "Please, install latest version from"
msgstr "Instale la versión mas reciente desde el"

#: templates/uds/index.html:72
msgid "Java website"
msgstr "Sitio Web de Java"

#: templates/uds/index.html:72
msgid "and restart browser"
msgstr "y reinicie el navegador"

#: templates/uds/index.html:78
msgid "Ip"
msgstr "IP"

#: templates/uds/index.html:79
msgid "Networks"
msgstr "Redes"

#: templates/uds/index.html:80
msgid "Transports"
msgstr "Transportes"

#: templates/uds/internal_page.html:34 templates/uds/prefs.html:12
msgid "Preferences"
msgstr "Preferencias"

#: templates/uds/internal_page.html:40
msgid "Log out"
msgstr "Desconectar"

#: templates/uds/login.html:6
msgid "Login to UDS"
msgstr "Acceder a UDS"

#: templates/uds/login.html:78
msgid "Login"
msgstr "Acceder"

#: templates/uds/login.html:83
msgid "Login data"
msgstr "Datos de acceso"

#: templates/uds/login.html:86
msgid "Enter"
msgstr "Entrar"

#: templates/uds/login.html:93
msgid "Back to login"
msgstr "Volver a iniciar sesión"

#: templates/uds/prefs.html:6
msgid "UDS User Preferences"
msgstr "UDS Preferencias de usuario "

#: templates/uds/prefs.html:16
msgid "Save Preferences"
msgstr "Guardar Preferencias"

#: templates/uds/service_not_ready.html:6
msgid "Service not ready at this moment. Please, try again in a while."
msgstr ""
"El servicio no está disponible en estos momentos. Por favor, intentelo de "
"nuevo pasado unos instantes."

#: templates/uds/snippets/admin_user.html:4
msgid "Admin"
msgstr "Admin"

#: templates/uds/snippets/back_to_list.html:3
msgid "Back to services list"
msgstr "Volver a la lista de servicios"

#: templates/uds/snippets/lang.html:9
msgid "Language"
msgstr "Idioma"

#: transports/NX/NXTransport.py:54
msgid "NX Transport (direct)"
msgstr "Transporte NX (directo)"

#: transports/NX/NXTransport.py:56
msgid "NX Transport for direct connection"
msgstr "Transporte NX para conexión directa"

#: transports/NX/NXTransport.py:60 transports/RDP/RDPTransport.py:36
#: transports/RDP/TSRDPTransport.py:40
#: transports/RGS-enterprise/RGSTransport.py:41
#: transports/RGS-enterprise/TRGSTransport.py:46
#: transports/TSNX/TSNXTransport.py:65
msgid "Empty creds"
msgstr "Sin credenciales"

#: transports/NX/NXTransport.py:60 transports/RDP/RDPTransport.py:36
#: transports/RDP/TSRDPTransport.py:40
#: transports/RGS-enterprise/RGSTransport.py:41
#: transports/RGS-enterprise/TRGSTransport.py:46
#: transports/TSNX/TSNXTransport.py:65
msgid "If checked, the credentials used to connect will be emtpy"
msgstr ""
"Si está activada, las credenciales utilizadas para conectar estarán vacías"

#: transports/NX/NXTransport.py:61 transports/RDP/RDPTransport.py:37
#: transports/RDP/TSRDPTransport.py:41
#: transports/RGS-enterprise/RGSTransport.py:42
#: transports/RGS-enterprise/TRGSTransport.py:47
#: transports/TSNX/TSNXTransport.py:66
msgid "If not empty, this username will be always used as credential"
msgstr ""
"Si no está vacio, este nombre de usuario será utilizado como credencial fija"

#: transports/NX/NXTransport.py:62 transports/RDP/RDPTransport.py:38
#: transports/RDP/TSRDPTransport.py:42
#: transports/RGS-enterprise/RGSTransport.py:43
#: transports/RGS-enterprise/TRGSTransport.py:48
#: transports/TSNX/TSNXTransport.py:67
msgid "If not empty, this password will be always used as credential"
msgstr "Si no está vacio, este password será utiizado como credencial fija"

#: transports/NX/NXTransport.py:63 transports/TSNX/TSNXTransport.py:68
msgid "Listen port"
msgstr "Puerto de escucha"

#: transports/NX/NXTransport.py:63 transports/TSNX/TSNXTransport.py:68
msgid "Listening port of NX (ssh) at client machine"
msgstr "Puerto de escucha de NX (ssh) en el equipo cliente"

#: transports/NX/NXTransport.py:64 transports/TSNX/TSNXTransport.py:69
msgid "Connection"
msgstr "Conexión"

#: transports/NX/NXTransport.py:64 transports/TSNX/TSNXTransport.py:69
msgid "Connection speed for this transport (quality)"
msgstr "Velocidad de conexión de este transporte (calidad)"

#: transports/NX/NXTransport.py:71 transports/TSNX/TSNXTransport.py:76
msgid "Session"
msgstr "Sesiones"

#: transports/NX/NXTransport.py:71 transports/TSNX/TSNXTransport.py:76
msgid "Desktop session"
msgstr "Sesión de escritorio"

#: transports/NX/NXTransport.py:76 transports/TSNX/TSNXTransport.py:81
msgid "Disk Cache"
msgstr "Caché de disco"

#: transports/NX/NXTransport.py:76 transports/TSNX/TSNXTransport.py:81
msgid "Cache size en Mb stored at disk"
msgstr "Tamaño de ca Caché en MB almacenada en disco"

#: transports/NX/NXTransport.py:84 transports/TSNX/TSNXTransport.py:89
msgid "Memory Cache"
msgstr "Memoria Caché"

#: transports/NX/NXTransport.py:84 transports/TSNX/TSNXTransport.py:89
msgid "Cache size en Mb keept at memory"
msgstr "Tamaño  del Caché en Mb a mantener en memoria"

#: transports/NX/__init__.py:40 transports/TSNX/__init__.py:40
msgid "NX Protocol"
msgstr "Protocolo NX"

#: transports/NX/__init__.py:46
msgid "UDS Actor connector for NX <b>(requires nomachine packages)</b>"
msgstr "Conector de UDS Actor para NX <b>(requiere nomachine paquetes)</b>"

#: transports/NX/web.py:74
msgid ""
"In order to use this transport, you need to install first Nomachine Nx "
"Client version 3.5.x"
msgstr ""
"Para poder utilizar este transporte, necesita instalar primera Nomachine Nx "
"Cliente versión 3.5"

#: transports/NX/web.py:75
msgid "you can obtain it for your platform from"
msgstr "Usted puede obtener para su plataforma de"

#: transports/NX/web.py:75
msgid "nochamine web site"
msgstr "Sitio Web de Nomachine"

#: transports/RDP/RDPTransport.py:30
msgid "RDP Transport (direct)"
msgstr "Transporte RDP (directo)"

#: transports/RDP/RDPTransport.py:32
msgid "RDP Transport for direct connection"
msgstr "Transporte RDP para conexión directa"

#: transports/RDP/RDPTransport.py:39 transports/RDP/TSRDPTransport.py:43
#: transports/RGS-enterprise/RGSTransport.py:44
#: transports/RGS-enterprise/TRGSTransport.py:49
msgid ""
"If not empty, this domain will be always used as credential (used as DOMAIN"
"\\user)"
msgstr ""
"Si no está vacio, este domínio será usado como parte de las credenciales del "
"usuario (usado como DOMAIN\\user)"

#: transports/RDP/RDPTransport.py:40 transports/RDP/TSRDPTransport.py:44
msgid "Allow Smartcards"
msgstr "Permitir tarjetas inteligentes"

#: transports/RDP/RDPTransport.py:40 transports/RDP/TSRDPTransport.py:44
msgid "If checked, this transport will allow the use of smartcards"
msgstr ""
"Si está marcado, este transporte permitirá el uso de tarjetas inteligentes"

#: transports/RDP/RDPTransport.py:41 transports/RDP/TSRDPTransport.py:45
msgid "Allow Printers"
msgstr "Permitir impresoras"

#: transports/RDP/RDPTransport.py:41 transports/RDP/TSRDPTransport.py:45
msgid "If checked, this transport will allow the use of user printers"
msgstr ""
"Si está marcado, este transporte permitirá el uso de impresoras remotas"

#: transports/RDP/RDPTransport.py:42 transports/RDP/TSRDPTransport.py:46
msgid "Allow Drives"
msgstr "Permitir unidades"

#: transports/RDP/RDPTransport.py:42 transports/RDP/TSRDPTransport.py:46
msgid "If checked, this transport will allow the use of user drives"
msgstr ""
"Si está marcado, este transporte permitirá la redireccion de las unidades "
"locales a la máquina remota"

#: transports/RDP/RDPTransport.py:43 transports/RDP/TSRDPTransport.py:47
msgid "Allow Serials"
msgstr "Permitir series"

#: transports/RDP/RDPTransport.py:43 transports/RDP/TSRDPTransport.py:47
msgid "If checked, this transport will allow the use of user serial ports"
msgstr ""
"Si está marcado, este transporte permitirá la redirección de puertos serie"

#: transports/RDP/TSRDPTransport.py:31
msgid "RDP Transport (tunneled)"
msgstr "Transporte RDP (vía túnel)"

#: transports/RDP/TSRDPTransport.py:33
msgid "RDP Transport for tunneled connection"
msgstr "Transporte RDP para conexión vía túnel"

#: transports/RDP/TSRDPTransport.py:37
#: transports/RGS-enterprise/TRGSTransport.py:43
#: transports/TSNX/TSNXTransport.py:62
msgid "Tunnel server"
msgstr "Servidor de túnel"

#: transports/RDP/TSRDPTransport.py:37
#: transports/RGS-enterprise/TRGSTransport.py:43
#: transports/TSNX/TSNXTransport.py:62
msgid ""
"IP or Hostname of tunnel server send to client device (\"public\" ip) and "
"port. (use HOST:PORT format)"
msgstr ""
"IP o nombre de host del servidor de túnel enviar a dispositivo de cliente "
"(ip \"pública\") y puerto. (utilice el formato HOST: puerto)"

#: transports/RDP/TSRDPTransport.py:38
#: transports/RGS-enterprise/TRGSTransport.py:44
#: transports/TSNX/TSNXTransport.py:63
msgid "Tunnel host check"
msgstr "Verificación de host de túnel"

#: transports/RDP/TSRDPTransport.py:38
#: transports/RGS-enterprise/TRGSTransport.py:44
#: transports/TSNX/TSNXTransport.py:63
msgid ""
"If not empty, this server will be used to check if service is running before "
"assigning it to user. (use HOST:PORT format)"
msgstr ""
"Si no vacía, este servidor se utilizará para comprobar si el servicio se "
"ejecuta antes de asignarle al usuario. (utilice el formato HOST: puerto)"

#: transports/RDP/__init__.py:17
msgid "Remote Desktop Protocol"
msgstr "Protocolo de Escritorio remoto (RDP)"

#: transports/RDP/web.py:83
msgid "In order to use this service, you should first install CoRD."
msgstr "Para poder utilizar este servicio, primero debe instalar CoRD."

#: transports/RDP/web.py:84 transports/RGS-enterprise/web.py:82
msgid "You can obtain it from"
msgstr "Puede obtenerlo de"

#: transports/RDP/web.py:84
msgid "CoRD Website"
msgstr "Sitio Web de CoRD"

#: transports/RGS-enterprise/RGSTransport.py:34
msgid "RGS Transport (direct)"
msgstr "Transporte RGS (directo)"

#: transports/RGS-enterprise/RGSTransport.py:36
msgid "RGS Transport for direct connection"
msgstr "Transporte RGS para conexión directa"

#: transports/RGS-enterprise/RGSTransport.py:45
#: transports/RGS-enterprise/TRGSTransport.py:50
msgid "Image quality"
msgstr "Calidad de imagen"

#: transports/RGS-enterprise/RGSTransport.py:46
#: transports/RGS-enterprise/TRGSTransport.py:51
msgid "Quality of image codec (0-100)"
msgstr "Calidad del códec de imagen (0-100)"

#: transports/RGS-enterprise/RGSTransport.py:47
#: transports/RGS-enterprise/TRGSTransport.py:52
msgid "Adjustable Quality"
msgstr "Calidad ajustable"

#: transports/RGS-enterprise/RGSTransport.py:48
#: transports/RGS-enterprise/TRGSTransport.py:53
msgid "If checked, the image quality will be adjustable with bandwidth"
msgstr ""
"Si está activada, la calidad de imagen será ajustable con ancho de banda"

#: transports/RGS-enterprise/RGSTransport.py:49
#: transports/RGS-enterprise/TRGSTransport.py:54
msgid "Min. Adjustable Quality"
msgstr "Mín. calidad ajustable"

#: transports/RGS-enterprise/RGSTransport.py:50
#: transports/RGS-enterprise/TRGSTransport.py:55
msgid ""
"The lowest image quality applied to images to maintain the minimum update "
"rate."
msgstr ""
"La menor calidad de imagen aplicada a las imágenes para mantener la "
"actualización mínima tasa."

#: transports/RGS-enterprise/RGSTransport.py:51
#: transports/RGS-enterprise/TRGSTransport.py:56
msgid "Adjustable Frame Rate"
msgstr "Ajustable velocidad de fotogramas"

#: transports/RGS-enterprise/RGSTransport.py:52
#: transports/RGS-enterprise/TRGSTransport.py:57
msgid "Update rate threshold to begin adjusting image quality"
msgstr ""
"Umbral de velocidad de actualización para comenzar el ajuste de calidad de "
"imagen"

#: transports/RGS-enterprise/RGSTransport.py:53
#: transports/RGS-enterprise/TRGSTransport.py:58
msgid "Match Local Resolution"
msgstr "Resolución Local de partido"

#: transports/RGS-enterprise/RGSTransport.py:54
#: transports/RGS-enterprise/TRGSTransport.py:59
msgid ""
"Change the Sender's resolution to match the Receiver's resolution when "
"connecting"
msgstr ""
"Cambiar la resolución del remitente para que coincida con la resolución del "
"receptor cuando conexión"

#: transports/RGS-enterprise/RGSTransport.py:55
#: transports/RGS-enterprise/TRGSTransport.py:60
msgid "Redirect USB"
msgstr "Redirección USB"

#: transports/RGS-enterprise/RGSTransport.py:56
#: transports/RGS-enterprise/TRGSTransport.py:61
msgid "If checked, the USB will be redirected."
msgstr "Si está activada, se redirigirá el USB."

#: transports/RGS-enterprise/RGSTransport.py:57
#: transports/RGS-enterprise/TRGSTransport.py:62
msgid "Redirect Audio"
msgstr "Redirección de Audio"

#: transports/RGS-enterprise/RGSTransport.py:58
#: transports/RGS-enterprise/TRGSTransport.py:63
msgid "If checked, the Audio will be redirected."
msgstr "Si está activado, el audio será redirigido al cliente"

#: transports/RGS-enterprise/RGSTransport.py:59
#: transports/RGS-enterprise/TRGSTransport.py:64
msgid "Redirect Mic"
msgstr "Redirigir Mic"

#: transports/RGS-enterprise/RGSTransport.py:60
#: transports/RGS-enterprise/TRGSTransport.py:65
msgid "If checked, the Mic will be redirected."
msgstr "Si está activado. el micro será redirigido al cliente"

#: transports/RGS-enterprise/TRGSTransport.py:36
msgid "RGS Transport (tunneled)"
msgstr "Transporte RGS (vía túnel)"

#: transports/RGS-enterprise/TRGSTransport.py:38
msgid "RGS Transport for tunneled connection"
msgstr "Transporte RGS para conexión vía túnel"

#: transports/RGS-enterprise/web.py:81
msgid "In order to use this service, you should first install RGS Receiver."
msgstr ""
"Para poder utilizar este servicio, primero debe instalar el Receiver de RGS"

#: transports/RGS-enterprise/web.py:82
msgid "HP Website"
msgstr "Sitio Web de HP"

#: transports/TSNX/TSNXTransport.py:55
msgid "NX Transport (tunneled)"
msgstr "Transporte NX (vía túnel)"

#: transports/TSNX/TSNXTransport.py:57
msgid "NX Transport for tunneled connection"
msgstr "Transporte NX para conexión vía túnel"

#: web/errors.py:58
msgid "Unknown error"
msgstr "Error desconocido"

#: web/errors.py:59
msgid "Transport not found"
msgstr "Transporte no hallado"

#: web/errors.py:60
msgid "Service not found"
msgstr "Servicio no hallado"

#: web/errors.py:61 xmlrpc/auths/AdminAuth.py:171
msgid "Access denied"
msgstr "Acceso denegado"

#: web/errors.py:62
msgid ""
"Invalid service. The service is not available at this moment. Please, try "
"later"
msgstr ""
"Servicio invalido. El servicio no está disponible en estos momentos. Por "
"favor, intentelo de nuevo pasado unos instantes."

#: web/errors.py:63
msgid "Maximum services limit reached. Please, contact administrator"
msgstr ""
"Número máximo de servicios alcanzado. Por favor, contacte con su "
"administrador."

#: web/errors.py:64
msgid "You need to enable cookies to let this application work"
msgstr "Necesita habilitar los cookies para permitir funcionar esta aplicación"

#: web/errors.py:65
msgid "User service not found"
msgstr "Servicio de usuario no hallado"

#: web/errors.py:66
msgid "Authenticator not found"
msgstr "Autenticador no hallado"

#: web/errors.py:67 xmlrpc/auths/AdminAuth.py:169
msgid "Invalid authenticator"
msgstr "Autenticador Invalido"

#: web/views.py:334
msgid "Authenticator do not provides information"
msgstr "El autenticador no proporciona información alguna"

#: web/forms/LoginForm.py:59
msgid "Authenticator"
msgstr "Autenticador"

#: xmlrpc/auths/AdminAuth.py:113
msgid "Credentials no longer valid"
msgstr "Las credenciales ya no son válidas"

#: xmlrpc/auths/AdminAuth.py:149
msgid "Administration"
msgstr "Administración"

#: xmlrpc/auths/AdminAuth.py:164
msgid "Invalid credentials"
msgstr "Credenciales Invalidas"

#: xmlrpc/auths/Authenticators.py:106
msgid "Authenticator does not exists"
msgstr "El autenticador no existe"

#: xmlrpc/auths/Authenticators.py:161 xmlrpc/osmanagers/OSManagers.py:115
#: xmlrpc/services/ServiceProviders.py:115
#: xmlrpc/services/ServiceProviders.py:139 xmlrpc/services/Services.py:160
#: xmlrpc/services/Services.py:184 xmlrpc/transports/Networks.py:86
#: xmlrpc/transports/Networks.py:97
#, python-format
msgid "Name %s already exists"
msgstr "El nombre %s ya existe"

#: xmlrpc/auths/Authenticators.py:234
msgid "Authenticator do not supports search"
msgstr "El autenticador no soporta búsquedas"

#: xmlrpc/auths/Authenticators.py:240
msgid "Specified authenticator do not exists anymore. Please, reload gui"
msgstr ""
"Hacer autenticador especificado no existe ya. Por favor, vuelva a cargar la "
"interfaz gráfica de usuario"

#: xmlrpc/auths/Authenticators.py:244
msgid "BUG: Reached a point that should never have been reached!!!"
msgstr "BUG: Llegado a un punto que no debe nunca han alcanzado!!!"

#: xmlrpc/osmanagers/OSManagers.py:129
msgid "This os mnager is being used by deployed services"
msgstr "Este OS Manager está siendo utilizado por servicios desplegados"

#: xmlrpc/osmanagers/OSManagers.py:145
msgid "There is deployed services using this os manager"
msgstr "Existen servicios desplegados que utilizan este gestor de SO"

#: xmlrpc/osmanagers/OSManagers.py:147
msgid "Can't find os manager"
msgstr "No se puede hallar el gestor de SO"

#: xmlrpc/services/DeployedServices.py:52
msgid "Unknown"
msgstr "Desconocido"

#: xmlrpc/services/DeployedServices.py:112
#: xmlrpc/services/DeployedServices.py:176
#: xmlrpc/services/DeployedServices.py:195
#: xmlrpc/services/DeployedServices.py:211
#: xmlrpc/services/DeployedServices.py:225
#: xmlrpc/services/DeployedServices.py:252
#: xmlrpc/services/DeployedServices.py:266
msgid "Deployed Service does not exists"
msgstr "El servicio desplegado no existe"

#: xmlrpc/services/DeployedServices.py:209
msgid "Group does not exists"
msgstr "El grupo no existe"

#: xmlrpc/services/DeployedServices.py:237
msgid "Can't find deployed service"
msgstr "No puedo hallar el servicio desplegado"

#: xmlrpc/services/DeployedServices.py:250
msgid "Transport does not exists"
msgstr "El transporte no existe"

#: xmlrpc/services/DeployedServices.py:281
msgid "Deployed service does not exists"
msgstr "El servicio desplegado no existe"

#: xmlrpc/services/ServiceProviders.py:154
msgid "Can't delete service provider with services associated"
msgstr "No se puede borrar un proveedor de servicios con servicios asociados"

#: xmlrpc/services/ServiceProviders.py:157
msgid "Can't locate the service provider"
msgstr "No puedo hallar el proveedor de servicios"

#: xmlrpc/services/ServiceProviders.py:157 xmlrpc/services/Services.py:202
#: xmlrpc/transports/Networks.py:70 xmlrpc/transports/Networks.py:78
#: xmlrpc/transports/Networks.py:95
msgid "Please, refresh interface"
msgstr "Por favor, refresque la interfaz."

#: xmlrpc/services/Services.py:199
msgid "Can't delete services with deployed services associated"
msgstr "No se puede borrar un servicio con servicios desplegados asociados"

#: xmlrpc/services/Services.py:202
msgid "Can't locate the service"
msgstr "No puedo hallar el servicio"

#: xmlrpc/services/UserDeployedServices.py:94
#: xmlrpc/services/UserDeployedServices.py:110
msgid "The deployed service is not active"
msgstr "El servicio desplegado no está activo"

#: xmlrpc/services/UserDeployedServices.py:97
#: xmlrpc/services/UserDeployedServices.py:113
msgid "This service don't allows assignations"
msgstr "El servicio no admite asignaciones"

#: xmlrpc/services/UserDeployedServices.py:102
#: xmlrpc/services/UserDeployedServices.py:120
msgid "Deployed service not found!!! (refresh interface)"
msgstr "Servicio desplegado no hallado!!! (refresque la interfaz)"

#: xmlrpc/services/UserDeployedServices.py:122
msgid "User not found!!! (refresh interface)"
msgstr "Usuario no hallado (refresque la interfaz)"

#: xmlrpc/services/UserDeployedServices.py:141
msgid "No error"
msgstr "Sin errores"

#: xmlrpc/services/UserDeployedServices.py:147
msgid "User deployed service not found!!!"
msgstr "Servicio de usuario no hallado!!!"

#: xmlrpc/transports/Networks.py:70
msgid "Can't locate the transport"
msgstr "No puedo hallar el transporte"

#: xmlrpc/transports/Networks.py:78 xmlrpc/transports/Networks.py:95
msgid "Can't locate the network"
msgstr "No puedo hallar la red"

#~ msgid "None OS Manager"
#~ msgstr "Ningún gestor de OS"

#~ msgid "Os Manager with no actions"
#~ msgstr "Gestor de OS que no realiza ninguna acción"

#~ msgid "Base Service"
#~ msgstr "Servicio Base"

#~ msgid "None"
#~ msgstr "Ninguno"
