# Translations for french
#
# Copyright (c) 2012 Virtual Cable S.L.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, 
# are permitted provided that the following conditions are met:
#
#    * Redistributions of source code must retain the above copyright notice, 
#      this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright notice, 
#      this list of conditions and the following disclaimer in the documentation 
#      and/or other materials provided with the distribution.
#    * Neither the name of Virtual Cable S.L. nor the names of its contributors 
#      may be used to endorse or promote products derived from this software 
#      without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE 
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE 
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR 
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, 
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# Adolfo Gómez <dkmaster at dkmon dot com>, 2012.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2012-11-28 10:17+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n > 1)\n"

#: auths/ActiveDirectory_enterprise/Authenticator.py:29
#: auths/EDirectory_enterprise/Authenticator.py:60
#: auths/RegexLdap/Authenticator.py:49 auths/SimpleLDAP/Authenticator.py:49
#: services/OVirt/OVirtProvider.py:91
#: services/Vmware_enterprise/ServiceProviderVC.py:28
msgid "Host"
msgstr "Serveur"

#: auths/ActiveDirectory_enterprise/Authenticator.py:29
#: auths/EDirectory_enterprise/Authenticator.py:60
#: auths/RegexLdap/Authenticator.py:49 auths/SimpleLDAP/Authenticator.py:49
#: services/Vmware_enterprise/ServiceProviderVC.py:28
msgid "VMWare VC Server IP or Hostname"
msgstr "Le nom DNS ou l'adresse IP VC VMWare Server"

#: auths/ActiveDirectory_enterprise/Authenticator.py:30
#: auths/EDirectory_enterprise/Authenticator.py:62
#: auths/RegexLdap/Authenticator.py:51 auths/SimpleLDAP/Authenticator.py:51
msgid "Use SSL"
msgstr "Utiliser SSL"

#: auths/ActiveDirectory_enterprise/Authenticator.py:30
msgid "If checked, will use a ssl connection to Active Directory"
msgstr "Si elle est cochée, va utiliser une connexion SSL à Active Directory"

#: auths/ActiveDirectory_enterprise/Authenticator.py:31
#: auths/RegexLdap/Authenticator.py:52 auths/SimpleLDAP/Authenticator.py:52
msgid "Ldap User"
msgstr "Utilisateur LDAP"

#: auths/ActiveDirectory_enterprise/Authenticator.py:31
msgid ""
"Username with read privileges on the base selected (use USER@DOMAIN.DOM form "
"for this)"
msgstr ""
"Nom d'utilisateur avec des privilèges lire sur la base choisie (utiliser le "
"format USER@DOMAIN.DOMpour cela)"

#: auths/ActiveDirectory_enterprise/Authenticator.py:32
#: auths/ActiveDirectory_enterprise/Authenticator.py:50
#: auths/EDirectory_enterprise/Authenticator.py:64
#: auths/RegexLdap/Authenticator.py:53 auths/RegexLdap/Authenticator.py:76
#: auths/SimpleLDAP/Authenticator.py:53 auths/SimpleLDAP/Authenticator.py:77
#: osmanagers/WindowsOsManager/WinDomainOsManager.py:31
#: osmanagers/WindowsOsManager/WinRandomPassOsManager.py:30
#: services/OVirt/OVirtProvider.py:93
#: services/Vmware_enterprise/ServiceProviderVC.py:31
#: transports/NX/NXTransport.py:62 transports/RDP/RDPTransport.py:38
#: transports/RDP/TSRDPTransport.py:42
#: transports/RGS-enterprise/RGSTransport.py:43
#: transports/RGS-enterprise/TRGSTransport.py:48
#: transports/TSNX/TSNXTransport.py:67 web/forms/LoginForm.py:58
msgid "Password"
msgstr "Mot de passe"

#: auths/ActiveDirectory_enterprise/Authenticator.py:32
#: auths/EDirectory_enterprise/Authenticator.py:64
#: auths/RegexLdap/Authenticator.py:53 auths/SimpleLDAP/Authenticator.py:53
msgid "Password of the ldap user"
msgstr "Mot de passe de l'utilisateur ldap"

#: auths/ActiveDirectory_enterprise/Authenticator.py:33
#: auths/EDirectory_enterprise/Authenticator.py:65
#: auths/RegexLdap/Authenticator.py:54 auths/SimpleLDAP/Authenticator.py:54
#: services/OVirt/OVirtProvider.py:94
#: services/Vmware_enterprise/ServiceProviderVC.py:32
msgid "Timeout"
msgstr "Temporisation"

#: auths/ActiveDirectory_enterprise/Authenticator.py:33
#: auths/EDirectory_enterprise/Authenticator.py:65
#: auths/RegexLdap/Authenticator.py:54 auths/SimpleLDAP/Authenticator.py:54
msgid "Timeout in seconds of connection to LDAP"
msgstr "Délai en secondes de la connexion à LDAP"

#: auths/ActiveDirectory_enterprise/Authenticator.py:35
msgid "Active Directory Authenticator"
msgstr "Active Directory authentificateur"

#: auths/ActiveDirectory_enterprise/Authenticator.py:37
#, fuzzy
msgid "Authenticate against Active Directory"
msgstr "Authentificateur sur Active Directory"

#: auths/ActiveDirectory_enterprise/Authenticator.py:46
#: auths/EDirectory_enterprise/Authenticator.py:77
#: auths/RegexLdap/Authenticator.py:72 auths/SimpleLDAP/Authenticator.py:73
#: services/OVirt/OVirtProvider.py:92
#: services/Vmware_enterprise/ServiceProviderVC.py:30
#: transports/NX/NXTransport.py:61 transports/RDP/RDPTransport.py:37
#: transports/RDP/TSRDPTransport.py:41
#: transports/RGS-enterprise/RGSTransport.py:42
#: transports/RGS-enterprise/TRGSTransport.py:47
#: transports/TSNX/TSNXTransport.py:66 web/forms/LoginForm.py:57
msgid "Username"
msgstr "Nom d'utilisateur"

#: auths/ActiveDirectory_enterprise/Authenticator.py:48
#: auths/EDirectory_enterprise/Authenticator.py:79
#: auths/RegexLdap/Authenticator.py:74 auths/SAML_enterprise/SAML.py:113
#: auths/SimpleLDAP/Authenticator.py:75
msgid "Group"
msgstr "Groupe"

#: auths/ActiveDirectory_enterprise/Authenticator.py:61
#: auths/ActiveDirectory_enterprise/Authenticator.py:395
msgid "Must specify the username in the form USERNAME@DOMAIN.DOM"
msgstr ""
"Doit spécifier le nom d'utilisateur sous la forme NOMDEUTILISEUR@DOMAINE.DOM"

#: auths/ActiveDirectory_enterprise/Authenticator.py:127
#: auths/EDirectory_enterprise/Authenticator.py:123
#: auths/RegexLdap/Authenticator.py:159 auths/SimpleLDAP/Authenticator.py:158
msgid "Ldap connection error: "
msgstr "Erreur de connexion LDAP : "

#: auths/ActiveDirectory_enterprise/Authenticator.py:299
#: auths/ActiveDirectory_enterprise/Authenticator.py:345
#: auths/EDirectory_enterprise/Authenticator.py:243
#: auths/EDirectory_enterprise/Authenticator.py:286
#: auths/RegexLdap/Authenticator.py:249 auths/RegexLdap/Authenticator.py:292
#: auths/SimpleLDAP/Authenticator.py:269 auths/SimpleLDAP/Authenticator.py:313
msgid "Username not found"
msgstr "Nom d'utilisateur introuvable"

#: auths/ActiveDirectory_enterprise/Authenticator.py:332
#: auths/SimpleLDAP/Authenticator.py:302
msgid "Group not found"
msgstr "Groupe introuvable"

#: auths/ActiveDirectory_enterprise/Authenticator.py:364
#: auths/ActiveDirectory_enterprise/Authenticator.py:381
#: auths/EDirectory_enterprise/Authenticator.py:303
#: auths/RegexLdap/Authenticator.py:309 auths/SimpleLDAP/Authenticator.py:328
#: auths/SimpleLDAP/Authenticator.py:342
msgid "Too many results, be more specific"
msgstr "Trop de résultats, être plus spécifique"

#: auths/ActiveDirectory_enterprise/Authenticator.py:404
msgid "Domain seems to be incorrect, please check it"
msgstr "Domaine semble incorrect, veuillez vérifier"

#: auths/ActiveDirectory_enterprise/Authenticator.py:409
msgid "Ldap does not seem an Active Directory (do not have user objects)"
msgstr ""
"LDAP ne semble pas un serveur Active Directory (n'ont pas les objets "
"utilisateur)"

#: auths/ActiveDirectory_enterprise/Authenticator.py:417
msgid "Ldap does not seem an Active Directory (no not have group objects)"
msgstr ""
"LDAP ne semble pas un serveur Active Directory (ne pas ont les objets de "
"groupe)"

#: auths/ActiveDirectory_enterprise/Authenticator.py:425
msgid ""
"Ldap does not seem an Active Directory (do not have any user nor groups)"
msgstr ""
"LDAP ne semble pas un serveur Active Directory (n'ont pas tout utilisateur "
"ni les groupes)"

#: auths/ActiveDirectory_enterprise/Authenticator.py:430
#: auths/EDirectory_enterprise/Authenticator.py:358
#: auths/RegexLdap/Authenticator.py:384 auths/SimpleLDAP/Authenticator.py:423
msgid "Connection params seem correct, test was succesfully executed"
msgstr ""
"Connexion params semblent correctes, le test a été correctement exécutée"

#: auths/EDirectory_enterprise/Authenticator.py:61
#: auths/RegexLdap/Authenticator.py:50 auths/SimpleLDAP/Authenticator.py:50
#: services/Vmware_enterprise/ServiceProviderVC.py:29
msgid "Port"
msgstr "Port"

#: auths/EDirectory_enterprise/Authenticator.py:61
#: auths/RegexLdap/Authenticator.py:50 auths/SimpleLDAP/Authenticator.py:50
msgid "Ldap port (389 for non ssl, 636 for ssl normally"
msgstr "Port LDAP (389 non SSL, 636 pour ssl normalement"

#: auths/EDirectory_enterprise/Authenticator.py:62
#: auths/RegexLdap/Authenticator.py:51 auths/SimpleLDAP/Authenticator.py:51
msgid ""
"If checked, will use a ssl connection to ldap (if port is 389, will use in "
"fact port 636)"
msgstr ""
"Si cochée, utilise une connexion ssl à ldap (si le port est 389, utilisera "
"dans port de fait 636)"

#: auths/EDirectory_enterprise/Authenticator.py:63
#, fuzzy
msgid "Admin user"
msgstr "Admin"

#: auths/EDirectory_enterprise/Authenticator.py:63
#, fuzzy
msgid "Username with read privileges on the eDirectory"
msgstr ""
"Nom d'utilisateur avec des privilèges de lecture sur la base sélectionnée"

#: auths/EDirectory_enterprise/Authenticator.py:67
#, fuzzy
msgid "eDirectory Authenticator"
msgstr "Active Directory authentificateur"

#: auths/EDirectory_enterprise/Authenticator.py:69
#, fuzzy
msgid "Authenticate against eDirectory"
msgstr "Authentificateur sur Active Directory"

#: auths/EDirectory_enterprise/Authenticator.py:323
#: auths/RegexLdap/Authenticator.py:329 auths/SimpleLDAP/Authenticator.py:363
msgid "Ldap search base is incorrect"
msgstr "Base de recherche LDAP est incorrect"

#: auths/EDirectory_enterprise/Authenticator.py:328
#: auths/RegexLdap/Authenticator.py:334 auths/SimpleLDAP/Authenticator.py:368
msgid "Ldap user class seems to be incorrect (no user found by that class)"
msgstr ""
"Classe d'utilisateur LDAP semble incorrect (aucun utilisateur ne trouvé par "
"cette classe)"

#: auths/EDirectory_enterprise/Authenticator.py:336
#: auths/RegexLdap/Authenticator.py:350 auths/SimpleLDAP/Authenticator.py:384
msgid ""
"Ldap user id attribute seems to be incorrect (no user found by that "
"attribute)"
msgstr ""
"Attribut d'id utilisateur LDAP semble incorrect (aucun utilisateur ne "
"trouvée par qui attribut)"

#: auths/EDirectory_enterprise/Authenticator.py:344
msgid "Expected group attribute "
msgstr "Attribut du groupe prévu "

#: auths/EDirectory_enterprise/Authenticator.py:353
#, fuzzy
msgid ""
"Ldap user class or user id attr is probably wrong (Ldap is an eDirectory?)"
msgstr ""
"LDAP user utilisateur ou la classe id attr est probablement erroné (ne peut "
"pas trouver n'importe quel utilisateur avec les deux conditions)"

#: auths/IP/Authenticator.py:45 auths/IP/Authenticator.py:47
msgid "IP Authenticator"
msgstr "Authentificateur IP"

#: auths/IP/Authenticator.py:51
msgid "IP"
msgstr "IP "

#: auths/IP/Authenticator.py:52
msgid "IP Range"
msgstr "Plage d'adresses IP"

#: auths/IP/Authenticator.py:99 auths/InternalDB/Authenticator.py:102
msgid "All seems fine in the authenticator."
msgstr "Tout semble fine dans l'authentificateur."

#: auths/InternalDB/Authenticator.py:46
msgid "Internal Database"
msgstr "Base de données interne"

#: auths/InternalDB/Authenticator.py:48
msgid "Internal dabasase authenticator. Doesn't uses external sources"
msgstr "Dabasase interne authentificateur. N'utilise des sources externes"

#: auths/InternalDB/Authenticator.py:99
msgid "Internal structures seems ok"
msgstr "Les structures internes semble ok"

#: auths/RegexLdap/Authenticator.py:52 auths/SimpleLDAP/Authenticator.py:52
msgid "Username with read privileges on the base selected"
msgstr ""
"Nom d'utilisateur avec des privilèges de lecture sur la base sélectionnée"

#: auths/RegexLdap/Authenticator.py:55 auths/SimpleLDAP/Authenticator.py:55
msgid "Base"
msgstr "Base"

#: auths/RegexLdap/Authenticator.py:55 auths/SimpleLDAP/Authenticator.py:55
msgid "Common search base (used for \"users\" and \"groups\""
msgstr ""
"Recherche commune base (utilisé pour les « utilisateurs » et « groupes »"

#: auths/RegexLdap/Authenticator.py:56 auths/SimpleLDAP/Authenticator.py:56
msgid "User class"
msgstr "Classe utilisateur"

#: auths/RegexLdap/Authenticator.py:56 auths/SimpleLDAP/Authenticator.py:56
msgid "Class for LDAP users (normally posixAccount)"
msgstr "Classe pour les utilisateurs de LDAP (normalement posixAccount)"

#: auths/RegexLdap/Authenticator.py:57 auths/SimpleLDAP/Authenticator.py:57
msgid "User Id Attr"
msgstr "Utilisateur Id Attr"

#: auths/RegexLdap/Authenticator.py:57 auths/SimpleLDAP/Authenticator.py:57
msgid "Attribute that contains the user id"
msgstr "Attribut qui contient l'id utilisateur"

#: auths/RegexLdap/Authenticator.py:58 auths/SimpleLDAP/Authenticator.py:58
msgid "User Name Attr"
msgstr "Utilisateur nom Attr"

#: auths/RegexLdap/Authenticator.py:58 auths/SimpleLDAP/Authenticator.py:58
msgid "Attributes that contains the user name (list of comma separated values)"
msgstr ""
"Attributs qui contient le nom d'utilisateur (liste de valeurs séparées par "
"des virgules)"

#: auths/RegexLdap/Authenticator.py:59
msgid "Group Name Attr"
msgstr "Groupe nom Attr"

#: auths/RegexLdap/Authenticator.py:59
msgid "Attribute that contains the group name"
msgstr "Attribut qui contient le nom du groupe"

#: auths/RegexLdap/Authenticator.py:60
msgid "Regular Exp. for groups"
msgstr "Exp régulière pour les groupes"

#: auths/RegexLdap/Authenticator.py:60
msgid "Regular Expression to extract the group name"
msgstr "Expression régulière pour extraire le nom du groupe"

#: auths/RegexLdap/Authenticator.py:62
msgid "Regex LDAP Authenticator"
msgstr "Authentificateur LDAP Regex"

#: auths/RegexLdap/Authenticator.py:64
msgid "Regular Expressions LDAP authenticator"
msgstr "Authentificateur de LDAP d'Expressions régulière"

#: auths/RegexLdap/Authenticator.py:96
msgid "Invalid regular expression"
msgstr ""

#: auths/RegexLdap/Authenticator.py:342 auths/SimpleLDAP/Authenticator.py:376
msgid "Ldap group class seems to be incorrect (no group found by that class)"
msgstr ""
"Classe de groupe LDAP semble incorrect (aucun groupe ne trouvée par cette "
"classe)"

#: auths/RegexLdap/Authenticator.py:360 auths/SimpleLDAP/Authenticator.py:392
msgid ""
"Ldap group id attribute seems to be incorrect (no group found by that "
"attribute)"
msgstr ""
"Attribut d'id groupe LDAP semble incorrect (aucun groupe ne trouvée par qui "
"attribut)"

#: auths/RegexLdap/Authenticator.py:369 auths/SimpleLDAP/Authenticator.py:401
msgid ""
"Ldap user class or user id attr is probably wrong (can't find any user with "
"both conditions)"
msgstr ""
"LDAP user utilisateur ou la classe id attr est probablement erroné (ne peut "
"pas trouver n'importe quel utilisateur avec les deux conditions)"

#: auths/SAML_enterprise/SAML.py:79
#, fuzzy
msgid "SAML Authenticator"
msgstr "Authentificateur"

#: auths/SAML_enterprise/SAML.py:91
#, fuzzy
msgid "SAML (v2.0) Authenticator"
msgstr "Authentificateur"

#: auths/SAML_enterprise/SAML.py:110 templates/uds/internal_page.html:28
msgid "User"
msgstr "Utilisateur"

#: auths/SAML_enterprise/SAML.py:119
msgid "Private key"
msgstr ""

#: auths/SAML_enterprise/SAML.py:120
msgid ""
"Private key used for sign and encription, as generated in base 64 from "
"openssl"
msgstr ""

#: auths/SAML_enterprise/SAML.py:121
msgid "Certificate"
msgstr ""

#: auths/SAML_enterprise/SAML.py:122
msgid "Server certificate (public), , as generated in base 64 from openssl"
msgstr ""

#: auths/SAML_enterprise/SAML.py:123
msgid "IDP Metadata"
msgstr ""

#: auths/SAML_enterprise/SAML.py:124
msgid ""
"You can enter here the URL or the IDP metadata or the metadata itself (xml)"
msgstr ""

#: auths/SAML_enterprise/SAML.py:126
msgid "Entity ID"
msgstr ""

#: auths/SAML_enterprise/SAML.py:127
msgid "ID of the SP. If left blank, this will be autogenerated from server URL"
msgstr ""

#: auths/SAML_enterprise/SAML.py:129
#, fuzzy
msgid "User name attrs"
msgstr "Utilisateur nom Attr"

#: auths/SAML_enterprise/SAML.py:130
#, fuzzy
msgid "Fields from where to extract user name"
msgstr "Expression régulière pour extraire le nom du groupe"

#: auths/SAML_enterprise/SAML.py:132
#, fuzzy
msgid "Group name attrs"
msgstr "Groupe nom Attr"

#: auths/SAML_enterprise/SAML.py:133
#, fuzzy
msgid "Fields from where to extract the groups"
msgstr "Expression régulière pour extraire le nom du groupe"

#: auths/SAML_enterprise/SAML.py:135
#, fuzzy
msgid "Real name attrs"
msgstr "Utilisateur nom Attr"

#: auths/SAML_enterprise/SAML.py:136
#, fuzzy
msgid "Fields from where to extract the real name"
msgstr "Expression régulière pour extraire le nom du groupe"

#: auths/SAML_enterprise/SAML.py:159
msgid ""
"Server certificate should be a valid PEM (PEM certificates starts with -----"
"BEGIN CERTIFICATE-----)"
msgstr ""

#: auths/SAML_enterprise/SAML.py:164
msgid "Invalid server certificate. "
msgstr ""

#: auths/SAML_enterprise/SAML.py:167
msgid ""
"Private key should be a valid PEM (PEM private keys starts with -----BEGIN "
"RSA PRIVATE KEY-----"
msgstr ""

#: auths/SAML_enterprise/SAML.py:196
msgid "Can't fetch url {0}: {1}"
msgstr ""

#: auths/SAML_enterprise/SAML.py:207
msgid " (obtained from URL)"
msgstr ""

#: auths/SAML_enterprise/SAML.py:208
msgid "XML do not seems valid for IDP Metadata "
msgstr ""

#: auths/SAML_enterprise/SAML.py:224
msgid "Can't access idp metadata"
msgstr ""

#: auths/SimpleLDAP/Authenticator.py:59
msgid "Group class"
msgstr "Groupe classe"

#: auths/SimpleLDAP/Authenticator.py:59
msgid "Class for LDAP groups (normally poxisGroup)"
msgstr "Classe pour les groupes LDAP (normalement poxisGroup)"

#: auths/SimpleLDAP/Authenticator.py:60
msgid "Group Id Attr"
msgstr "Groupe Id Attr"

#: auths/SimpleLDAP/Authenticator.py:60
msgid "Attribute that contains the group id"
msgstr "Attribut qui contient l'id de groupe"

#: auths/SimpleLDAP/Authenticator.py:61
msgid "Group membership attr"
msgstr "Groupe adhésion attr"

#: auths/SimpleLDAP/Authenticator.py:61
msgid "Attribute of the group that contains the users belonging to it"
msgstr "Attribut du groupe qui contient les utilisateurs appartenant à elle"

#: auths/SimpleLDAP/Authenticator.py:63
msgid "SimpleLDAP Authenticator"
msgstr "Authentificateur SimpleLDAP"

#: auths/SimpleLDAP/Authenticator.py:65
msgid "Simple LDAP authenticator"
msgstr "Simple authentificateur LDAP"

#: auths/SimpleLDAP/Authenticator.py:410
msgid ""
"Ldap group class or group id attr is probably wrong (can't find any group "
"with both conditions)"
msgstr ""
"LDAP groupe classe ou groupe id attr est probablement erroné (ne peut pas "
"trouver n'importe quel groupe avec les deux conditions)"

#: auths/SimpleLDAP/Authenticator.py:417
msgid "Can't locate any group with the membership attribute specified"
msgstr ""
"Ne peut pas localiser n'importe quel groupe avec l'attribut d'appartenance "
"spécifié"

#: core/BaseModule.py:196
msgid "No connection checking method is implemented."
msgstr "Aucun lien vérifier la méthode n'est implémentée."

#: core/BaseModule.py:253
msgid "No check method provided."
msgstr "Aucune méthode de vérification fournie."

#: core/managers/PublicationManager.py:152
msgid ""
"Already publishing. Wait for previous publication to finish and try again"
msgstr ""
"Déjà la publication. Attendez une publication antérieure de terminer et "
"réessayez"

#: core/managers/PublicationManager.py:165
msgid "Can't cancel non running publication"
msgstr "Ne peut annuler la publication non courante"

#: core/managers/PublicationManager.py:183
msgid "Can't unpublish non usable publication"
msgstr "Ne peut annuler la publication publication non utilisable"

#: core/managers/PublicationManager.py:186
msgid "Can't unpublish publications with services in process"
msgstr ""
"Ne peut annuler la publication des publications avec services de processus"

#: core/managers/UserPrefsManager.py:254
msgid "Screen Size"
msgstr "Taille de l'écran"

#: core/managers/UserPrefsManager.py:258
msgid "Full Screen"
msgstr "Plein écran"

#: core/managers/UserPrefsManager.py:261
msgid "Screen colors"
msgstr "Couleurs de l'écran"

#: core/managers/UserPrefsManager.py:262
msgid "8 bits"
msgstr "8 bits"

#: core/managers/UserPrefsManager.py:263
msgid "16 bits"
msgstr "16 bits"

#: core/managers/UserPrefsManager.py:264
msgid "24 bits"
msgstr "24 bits"

#: core/managers/UserPrefsManager.py:265
msgid "32 bits"
msgstr "32 bits"

#: core/managers/UserServiceManager.py:303
msgid "Can't cancel non running operation"
msgstr "Ne peut annuler une opération non courante"

#: core/managers/UserServiceManager.py:322
msgid "Can't remove a non active element"
msgstr "Impossible de supprimer un élément non actif"

#: core/managers/UserServiceManager.py:335
msgid "Can't remove nor cancel {0} cause its states doesn't allows it"
msgstr "Ne peut pas supprimer ni annuler {0} cause ses États ne lui permet pas"

#: core/osmanagers/BaseOsManager.py:49
msgid "Base OS Manager"
msgstr "Gestionnaire d'OS de base"

#: core/osmanagers/BaseOsManager.py:51
msgid "Base Manager"
msgstr "Gestionnaire de base de"

#: core/transports/BaseTransport.py:113
msgid "Transport empty"
msgstr "Transport vide"

#: core/util/State.py:59
msgid "Active"
msgstr "Active"

#: core/util/State.py:59
msgid "Inactive"
msgstr "Inactif"

#: core/util/State.py:59
msgid "Blocked"
msgstr "Bloqué"

#: core/util/State.py:59
msgid "Waiting publication"
msgstr "Attente de publication"

#: core/util/State.py:60
msgid "In preparation"
msgstr "En préparation"

#: core/util/State.py:60
msgid "Valid"
msgstr "Valide"

#: core/util/State.py:61
msgid "Waiting for removal"
msgstr "Attente d'enlèvement"

#: core/util/State.py:61
msgid "Removing"
msgstr "Suppression"

#: core/util/State.py:61
msgid "Removed"
msgstr "Supprimé"

#: core/util/State.py:61
msgid "Canceled"
msgstr "Annulée"

#: core/util/State.py:62
msgid "Canceling"
msgstr "Annulation"

#: core/util/State.py:62 templates/uds/error.html:6
#: templates/uds/error.html.py:11
msgid "Error"
msgstr "Erreur"

#: core/util/State.py:62
msgid "Running"
msgstr "En cours d'exécution"

#: core/util/State.py:62
msgid "Finished"
msgstr "Fini"

#: core/util/State.py:62
msgid "Waiting execution"
msgstr "Exécution en attente"

#: osmanagers/LinuxOsManager/LinuxOsManager.py:45
msgid "Linux OS Manager"
msgstr "Gestionnaire de système d'exploitation Linux"

#: osmanagers/LinuxOsManager/LinuxOsManager.py:47
msgid ""
"Os Manager to control linux virtual machines (basically renames machine and "
"notify state)"
msgstr ""
"Gestionnaire de l'os pour contrôler les machines virtuelles de linux "
"(essentiellement renomme machine et notifier l'État)"

#: osmanagers/LinuxOsManager/LinuxOsManager.py:50
#: osmanagers/WindowsOsManager/WindowsOsManager.py:41
msgid "On Logout"
msgstr "Sur Logout"

#: osmanagers/LinuxOsManager/LinuxOsManager.py:50
#: osmanagers/WindowsOsManager/WindowsOsManager.py:41
msgid "What to do when user logout from service"
msgstr "Que faire quand déconnexion de l'utilisateur du service"

#: osmanagers/LinuxOsManager/LinuxOsManager.py:51
#: osmanagers/WindowsOsManager/WindowsOsManager.py:42
msgid "Keep service assigned"
msgstr "Garder les services affectés"

#: osmanagers/LinuxOsManager/LinuxOsManager.py:52
#: osmanagers/WindowsOsManager/WindowsOsManager.py:43
msgid "Remove service"
msgstr "Retirer du service"

#: osmanagers/LinuxOsManager/__init__.py:43
msgid "UDS Actor for linux machines <b>(Requires python 2.6 or greater)"
msgstr ""
"Acteur de l'UDS pour linux machines <b>(nécessite le python 2.6 ou plus)"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:23
msgid "Windows Domain OS Manager"
msgstr "Gestionnaire de système d'exploitation pour le domaine Windows"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:25
msgid ""
"Os Manager to control windows machines with domain. (Basically renames "
"machine)"
msgstr ""
"Os Manager pour contrôler les machines windows avec le domaine. "
"(Essentiellement renomme machine)"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:29
#: transports/RDP/RDPTransport.py:39 transports/RDP/TSRDPTransport.py:43
#: transports/RGS-enterprise/RGSTransport.py:44
#: transports/RGS-enterprise/TRGSTransport.py:49
msgid "Domain"
msgstr "Domaine"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:29
msgid "Domain to join machines to (better use dns form of domain)"
msgstr ""
"Domaine de rejoindre les machines (mieux utiliser le formulaire de dns du "
"domaine)"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:30
#: osmanagers/WindowsOsManager/WinRandomPassOsManager.py:29
msgid "Account"
msgstr "Compte"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:30
msgid "Account with rights to add machines to domain"
msgstr "Compte avec droits d'ajouter des machines à domaine"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:31
msgid "Password of the account"
msgstr "Mot de passe du compte"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:32
msgid "OU"
msgstr "OU"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:32
msgid ""
"Organizational unit where to add machines in domain (check it before using "
"it)"
msgstr ""
"Unité organisationnelle où ajouter des machines dans le domaine (vérifier il "
"avant d'utiliser GTG"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:40
msgid "Must provide a domain!!!"
msgstr "Doit fournir un domaine!!!"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:42
msgid "Must provide an account to add machines to domain!!!"
msgstr "Doit fournir un compte pour ajouter des machines à domaine!!!"

#: osmanagers/WindowsOsManager/WinDomainOsManager.py:44
#: osmanagers/WindowsOsManager/WinRandomPassOsManager.py:41
msgid "Must provide a password for the account!!!"
msgstr "Doit fournir un mot de passe du compte!!!"

#: osmanagers/WindowsOsManager/WinRandomPassOsManager.py:23
#, fuzzy
msgid "Windows Random Password OS Manager"
msgstr "Gestionnaire de système d'exploitation pour le domaine Windows"

#: osmanagers/WindowsOsManager/WinRandomPassOsManager.py:25
#, fuzzy
msgid ""
"Os Manager to control windows machines, with user password set randomly."
msgstr ""
"Os Manager pour contrôler les machines windows avec le domaine. "
"(Essentiellement renomme machine)"

#: osmanagers/WindowsOsManager/WinRandomPassOsManager.py:29
msgid "User account to change password"
msgstr ""

#: osmanagers/WindowsOsManager/WinRandomPassOsManager.py:30
#, fuzzy
msgid "Current (template) password of the user account"
msgstr "Doit fournir un mot de passe du compte!!!"

#: osmanagers/WindowsOsManager/WinRandomPassOsManager.py:39
#, fuzzy
msgid "Must provide an user account!!!"
msgstr "Doit fournir un mot de passe du compte!!!"

#: osmanagers/WindowsOsManager/WindowsOsManager.py:36
msgid "Windows Basic OS Manager"
msgstr "Gestionnaire de base de Windows OS"

#: osmanagers/WindowsOsManager/WindowsOsManager.py:38
msgid ""
"Os Manager to control windows machines without domain. (Basically renames "
"machine)"
msgstr ""
"Os Manager pour contrôler les machines windows sans domaine. "
"(Essentiellement renomme machine)"

#: osmanagers/WindowsOsManager/WindowsOsManager.py:52
msgid "Length must be numeric!!"
msgstr "La longueur doit être numérique!!"

#: osmanagers/WindowsOsManager/WindowsOsManager.py:54
msgid "Length must be betwen 1 and six"
msgstr "La longueur doit être images 1 et six"

#: osmanagers/WindowsOsManager/__init__.py:25
msgid ""
"UDS Actor for windows machines <b>(Important!! Requires .net framework 3.5 "
"sp1)</b>"
msgstr ""
"Acteur de l'UDS pour machines windows <b>(Important!! Nécessite le .net "
"framework 3.5 SP1)</b>"

#: services/OVirt/OVirtLinkedService.py:56
#, fuzzy
msgid "oVirt Linked Clone"
msgstr "Base de clone lié VMWare"

#: services/OVirt/OVirtLinkedService.py:60
msgid "oVirt Services based on templates and COW"
msgstr ""

#: services/OVirt/OVirtLinkedService.py:77
#: services/Vmware_enterprise/VCLinkedCloneService.py:70
msgid "Number of desired machines to keep running waiting for a user"
msgstr "Nombre de machines désirés de courir d'attente pour un utilisateur."

#: services/OVirt/OVirtLinkedService.py:83
#: services/Vmware_enterprise/VCLinkedCloneService.py:72
msgid "Number of desired machines to keep suspended waiting for use"
msgstr ""
"Nombre de machines désirés pour garder suspendu en attente pour utilisation"

#: services/OVirt/OVirtLinkedService.py:99
#: services/Vmware_enterprise/VCLinkedCloneService.py:48
#, fuzzy
msgid "Base Machine"
msgstr "Gestionnaire de base de"

#: services/OVirt/OVirtLinkedService.py:99
#, fuzzy
msgid "Service base machine"
msgstr "Machine de base"

#: services/OVirt/OVirtLinkedService.py:100
msgid "Cluster"
msgstr ""

#: services/OVirt/OVirtLinkedService.py:106
msgid "Cluster to contain services"
msgstr ""

#: services/OVirt/OVirtLinkedService.py:109
#, fuzzy
msgid "Datastore Domain"
msgstr "Magasins de données"

#: services/OVirt/OVirtLinkedService.py:110
#, fuzzy
msgid "Datastore domain where to publish and put incrementals"
msgstr "Magasins de données où mettre des sauvegardes incrémentielles"

#: services/OVirt/OVirtLinkedService.py:112
#: services/Vmware_enterprise/VCLinkedCloneService.py:49
msgid "Memory (Mb)"
msgstr "Mémoire (Mb)"

#: services/OVirt/OVirtLinkedService.py:113
msgid "Memory assigned to machines"
msgstr ""

#: services/OVirt/OVirtLinkedService.py:115
#, fuzzy
msgid "Memory Guaranteed (Mb)"
msgstr "Mémoire (Mb)"

#: services/OVirt/OVirtLinkedService.py:116
msgid "Physical memory guaranteed to machines"
msgstr ""

#: services/OVirt/OVirtLinkedService.py:118
#: services/Vmware_enterprise/VCLinkedCloneService.py:53
msgid "Machine Names"
msgstr "Noms de machine"

#: services/OVirt/OVirtLinkedService.py:119
#: services/Vmware_enterprise/VCLinkedCloneService.py:54
msgid "Name Length"
msgstr "Longueur du nom"

#: services/OVirt/OVirtLinkedService.py:120
#: services/Vmware_enterprise/VCLinkedCloneService.py:55
msgid "Length of numeric part for the names of this machines (betwen 3 and 6"
msgstr ""
"Longueur de la partie numérique pour les noms de ces machines (images 3 et 6"

#: services/OVirt/OVirtLinkedService.py:122
msgid "Display"
msgstr ""

#: services/OVirt/OVirtLinkedService.py:123
msgid "Display type (only for administration pourposses)"
msgstr ""

#: services/OVirt/OVirtLinkedService.py:143
#: services/Vmware_enterprise/VCLinkedCloneService.py:93
msgid "The length of basename plus length must not be greater than 15"
msgstr ""
"La longueur du nom de base plus la longueur ne doit pas être supérieure à 15"

#: services/OVirt/OVirtLinkedService.py:145
#: services/Vmware_enterprise/VCLinkedCloneService.py:95
msgid "The machine name can't be only numbers"
msgstr "Nom de l'ordinateur ne peut pas être uniquement des nombres"

#: services/OVirt/OVirtProvider.py:72
#, fuzzy
msgid "oVirt Platform Provider"
msgstr "VMWare Virtual Center fournisseur"

#: services/OVirt/OVirtProvider.py:76
#, fuzzy
msgid "oVirt platform service provider"
msgstr "Impossible de trouver le fournisseur de services"

#: services/OVirt/OVirtProvider.py:91
#, fuzzy
msgid "oVirt Server IP or Hostname"
msgstr "Le nom DNS ou l'adresse IP VC VMWare Server"

#: services/OVirt/OVirtProvider.py:92
#, fuzzy
msgid "User with valid privileges on oVirt, (use \"user@domain\" form)"
msgstr "Utilisateur avec des privilèges valides sur VC"

#: services/OVirt/OVirtProvider.py:93
#, fuzzy
msgid "Password of the user of oVirt"
msgstr "Mot de passe de l'utilisateur de la Croix de Victoria"

#: services/OVirt/OVirtProvider.py:94
#: services/Vmware_enterprise/ServiceProviderVC.py:32
msgid "Timeout in seconds of connection to VC"
msgstr "Délai en secondes de connexion à VC"

#: services/OVirt/OVirtProvider.py:95
#: services/Vmware_enterprise/ServiceProviderVC.py:33
msgid "Macs range"
msgstr "Gamme Mac"

#: services/OVirt/OVirtProvider.py:96
#: services/Vmware_enterprise/ServiceProviderVC.py:34
msgid "Range of valids macs for created machines"
msgstr "Gamme de Mac valides pour les machines créés"

#: services/OVirt/OVirtProvider.py:395
msgid "Connection test successful"
msgstr ""

#: services/OVirt/OVirtProvider.py:396
#: services/Vmware_enterprise/ServiceProviderVC.py:120
msgid "Connection failed. Check connection params"
msgstr "Échec de la connexion. Vérifiez la connexion params"

#: services/OVirt/OVirtPublication.py:85
#, fuzzy
msgid "UDS pub for {0} at {1}"
msgstr "Publication de l'UDS pour {0} créé à {1}"

#: services/PhysicalMachines/IPMachineDeployed.py:57
msgid "IP "
msgstr "IP "

#: services/PhysicalMachines/IPMachinesService.py:46
msgid "List of IPS"
msgstr "Liste des IPS"

#: services/PhysicalMachines/IPMachinesService.py:49
msgid "Physical machines accesed by ip"
msgstr "Accesed de machines physiques par ip"

#: services/PhysicalMachines/IPMachinesService.py:51
msgid "This service provides access to POWERED-ON Machines by ip"
msgstr "Ce service permet d'accéder aux machines SOUS-TENSION par ip"

#: services/Sample/SampleProvider.py:138
msgid "Methuselah is not alive!!! :-)"
msgstr "Mathusalem n'est pas vivant!!! :-)"

#: services/Sample/SampleProvider.py:178
msgid "Nothing tested, but all went fine.."
msgstr "Rien à l'épreuve, mais tout s'est bien passé..."

#: services/Sample/SamplePublication.py:195
msgid "Random integer was 9!!! :-)"
msgstr "Nombre entier aléatoire était 9!!! :-)"

#: services/Vmware_enterprise/Helpers.py:72
msgid "Local"
msgstr "Local"

#: services/Vmware_enterprise/Helpers.py:74
msgid "Remote"
msgstr "Distant"

#: services/Vmware_enterprise/PublicationVC.py:37
msgid "Publication"
msgstr "Publication"

#: services/Vmware_enterprise/PublicationVC.py:38
#, fuzzy
msgid "UDS Publication for {0} created at {1}"
msgstr "Publication de l'UDS pour {0} créé à {1}"

#: services/Vmware_enterprise/ServiceProviderVC.py:29
msgid "VMWare VC Server Port (usually 443)"
msgstr "Port du serveur VMWare VC (habituellement 443)"

#: services/Vmware_enterprise/ServiceProviderVC.py:30
#, fuzzy
msgid "User with valid privileges on VC"
msgstr ""
"Nom d'utilisateur avec des privilèges de lecture sur la base sélectionnée"

#: services/Vmware_enterprise/ServiceProviderVC.py:31
#, fuzzy
msgid "Password of the user of the VC"
msgstr "Mot de passe de l'utilisateur de la Croix de Victoria"

#: services/Vmware_enterprise/ServiceProviderVC.py:39
#, fuzzy
msgid "VMWare Virtual Center Provider"
msgstr "VmwareVC fournisseur : "

#: services/Vmware_enterprise/ServiceProviderVC.py:41
msgid "Provides connection to Virtual Center Services"
msgstr "Fournit la connexion aux Services du Centre virtuel"

#: services/Vmware_enterprise/ServiceProviderVC.py:110
msgid "Error testing connection"
msgstr "Connexion essai erreur"

#: services/Vmware_enterprise/ServiceProviderVC.py:113
msgid "VmwareVC Provider: "
msgstr "VmwareVC fournisseur : "

#: services/Vmware_enterprise/ServiceProviderVC.py:119
msgid "Connection params ok"
msgstr "Connexion params ok"

#: services/Vmware_enterprise/VCLinkedCloneService.py:28
msgid "Datacenter"
msgstr "Datacenter"

#: services/Vmware_enterprise/VCLinkedCloneService.py:34
msgid "Datacenter containing base machine"
msgstr "Machine de base contenant Datacenter"

#: services/Vmware_enterprise/VCLinkedCloneService.py:36
msgid "Network"
msgstr "Réseau"

#: services/Vmware_enterprise/VCLinkedCloneService.py:37
msgid ""
"If more than 1 interface is found in machine, use one on this network as main"
msgstr ""
"Si plus de 1 interface est trouvé dans la machine, utilisez l'une sur ce "
"réseau comme principal"

#: services/Vmware_enterprise/VCLinkedCloneService.py:38
msgid "Pub. Resource Pool"
msgstr "Pub. Ressource Pool"

#: services/Vmware_enterprise/VCLinkedCloneService.py:38
msgid "Resource Pool where deploy clones"
msgstr "Ressource Pool déployer où les clones"

#: services/Vmware_enterprise/VCLinkedCloneService.py:39
msgid "Clones Folder"
msgstr "Dossier de clones"

#: services/Vmware_enterprise/VCLinkedCloneService.py:39
msgid "Folder where deploy clones"
msgstr "Dossier où déployer clones"

#: services/Vmware_enterprise/VCLinkedCloneService.py:40
msgid "Resource Pool"
msgstr "Ressource Pool"

#: services/Vmware_enterprise/VCLinkedCloneService.py:46
msgid "Resource Pool containing base machine"
msgstr "Machine base contenant de ressource Pool"

#: services/Vmware_enterprise/VCLinkedCloneService.py:48
msgid "Base machine for this service"
msgstr "Machine de base pour ce service."

#: services/Vmware_enterprise/VCLinkedCloneService.py:50
msgid "Memory for machines deployed from this service"
msgstr "Mémoire pour les machines déployés à partir de ce service"

#: services/Vmware_enterprise/VCLinkedCloneService.py:51
#, fuzzy
msgid "Datastores"
msgstr "Magasins de données"

#: services/Vmware_enterprise/VCLinkedCloneService.py:52
#, fuzzy
msgid "Datastores where to put incrementals"
msgstr "Magasins de données où mettre des sauvegardes incrémentielles"

#: services/Vmware_enterprise/VCLinkedCloneService.py:53
msgid "Base name for clones from this machine"
msgstr "Nom de base des clones de cette machine."

#: services/Vmware_enterprise/VCLinkedCloneService.py:62
#, fuzzy
msgid "VMWare Linked clone base"
msgstr "Base de clone lié VMWare"

#: services/Vmware_enterprise/VCLinkedCloneService.py:64
msgid ""
"This service provides access to Linked Clones machines on a Virtual Center"
msgstr ""
"Ce service donne accès aux machines de Clones liés sur un centre virtuel"

#: templates/404.html:4 templates/404.html.py:7
msgid "Page not found"
msgstr "Page non trouvée"

#: templates/404.html:9
msgid "Sorry, but the requested page could not be found."
msgstr "Désolé, mais la page demandée n'a pas pu être trouvée."

#: templates/uds/base.html:7
msgid "UDS"
msgstr "UDS"

#: templates/uds/detectJava.html:6
msgid "Login redirection"
msgstr ""

#: templates/uds/detectJava.html:38
msgid "Go to main page"
msgstr ""

#: templates/uds/downloads.html:8 templates/uds/snippets/admin_user.html:7
msgid "Downloads"
msgstr "Téléchargements"

#: templates/uds/downloads.html:11
msgid ""
"This page contains a list of downloadables provided by different modules"
msgstr ""
"Cette page contient une liste de téléchargeables fournis par différents "
"modules"

#: templates/uds/index.html:51
msgid "Services"
msgstr "Services"

#: templates/uds/index.html:70
msgid "Java not found"
msgstr "Java non trouvé"

#: templates/uds/index.html:71
msgid ""
"Java is not available on your browser, and the selected transport needs it."
msgstr ""
"Java n'est pas disponible sur votre navigateur, et le transport sélectionné "
"en a besoin."

#: templates/uds/index.html:72
msgid "Please, install latest version from"
msgstr "Veuillez installer une version plus récente de"

#: templates/uds/index.html:72
msgid "Java website"
msgstr "Site Web Java"

#: templates/uds/index.html:72
msgid "and restart browser"
msgstr "Redémarrez le navigateur"

#: templates/uds/index.html:78
msgid "Ip"
msgstr "IP"

#: templates/uds/index.html:79
msgid "Networks"
msgstr "Réseaux"

#: templates/uds/index.html:80
msgid "Transports"
msgstr "Transports"

#: templates/uds/internal_page.html:34 templates/uds/prefs.html:12
msgid "Preferences"
msgstr "Préférences"

#: templates/uds/internal_page.html:40
msgid "Log out"
msgstr "Déconnexion"

#: templates/uds/login.html:6
msgid "Login to UDS"
msgstr "Connexion à UDS"

#: templates/uds/login.html:78
msgid "Login"
msgstr "Login"

#: templates/uds/login.html:83
msgid "Login data"
msgstr "Données de connexion"

#: templates/uds/login.html:86
msgid "Enter"
msgstr "Entrez"

#: templates/uds/login.html:93
msgid "Back to login"
msgstr "Retour à la connexion"

#: templates/uds/prefs.html:6
msgid "UDS User Preferences"
msgstr "Préférences de l'utilisateur UDS"

#: templates/uds/prefs.html:16
msgid "Save Preferences"
msgstr "Enregistrer les préférences"

#: templates/uds/service_not_ready.html:6
msgid "Service not ready at this moment. Please, try again in a while."
msgstr ""
"Le service n'est pas prêt à ce moment. S'il vous plaît, essayez à nouveau de "
"temps en temps."

#: templates/uds/snippets/admin_user.html:4
msgid "Admin"
msgstr "Admin"

#: templates/uds/snippets/back_to_list.html:3
msgid "Back to services list"
msgstr "Retour à la liste de services"

#: templates/uds/snippets/lang.html:9
msgid "Language"
msgstr "Langue"

#: transports/NX/NXTransport.py:54
msgid "NX Transport (direct)"
msgstr "NX Transport (direct)"

#: transports/NX/NXTransport.py:56
msgid "NX Transport for direct connection"
msgstr "NX Transport pour une connexion directe"

#: transports/NX/NXTransport.py:60 transports/RDP/RDPTransport.py:36
#: transports/RDP/TSRDPTransport.py:40
#: transports/RGS-enterprise/RGSTransport.py:41
#: transports/RGS-enterprise/TRGSTransport.py:46
#: transports/TSNX/TSNXTransport.py:65
msgid "Empty creds"
msgstr "Références vide"

#: transports/NX/NXTransport.py:60 transports/RDP/RDPTransport.py:36
#: transports/RDP/TSRDPTransport.py:40
#: transports/RGS-enterprise/RGSTransport.py:41
#: transports/RGS-enterprise/TRGSTransport.py:46
#: transports/TSNX/TSNXTransport.py:65
msgid "If checked, the credentials used to connect will be emtpy"
msgstr ""
"Si coché, les informations d'identification utilisées pour se connecter sera "
"vide"

#: transports/NX/NXTransport.py:61 transports/RDP/RDPTransport.py:37
#: transports/RDP/TSRDPTransport.py:41
#: transports/RGS-enterprise/RGSTransport.py:42
#: transports/RGS-enterprise/TRGSTransport.py:47
#: transports/TSNX/TSNXTransport.py:66
msgid "If not empty, this username will be always used as credential"
msgstr ""
"Si ce n'est vide, ce nom d'utilisateur sera toujours utilisé comme des "
"titres de compétences"

#: transports/NX/NXTransport.py:62 transports/RDP/RDPTransport.py:38
#: transports/RDP/TSRDPTransport.py:42
#: transports/RGS-enterprise/RGSTransport.py:43
#: transports/RGS-enterprise/TRGSTransport.py:48
#: transports/TSNX/TSNXTransport.py:67
msgid "If not empty, this password will be always used as credential"
msgstr ""
"Si ce n'est vide, ce mot de passe sera toujours utilisé comme des titres de "
"compétences"

#: transports/NX/NXTransport.py:63 transports/TSNX/TSNXTransport.py:68
msgid "Listen port"
msgstr "Écouter le port"

#: transports/NX/NXTransport.py:63 transports/TSNX/TSNXTransport.py:68
msgid "Listening port of NX (ssh) at client machine"
msgstr "Écoute le port de NX (ssh) à la machine client"

#: transports/NX/NXTransport.py:64 transports/TSNX/TSNXTransport.py:69
msgid "Connection"
msgstr "Connexion"

#: transports/NX/NXTransport.py:64 transports/TSNX/TSNXTransport.py:69
msgid "Connection speed for this transport (quality)"
msgstr "Vitesse de connexion pour ce transport (qualité)"

#: transports/NX/NXTransport.py:71 transports/TSNX/TSNXTransport.py:76
msgid "Session"
msgstr "Session"

#: transports/NX/NXTransport.py:71 transports/TSNX/TSNXTransport.py:76
msgid "Desktop session"
msgstr "Session de bureau"

#: transports/NX/NXTransport.py:76 transports/TSNX/TSNXTransport.py:81
msgid "Disk Cache"
msgstr "Cache disque"

#: transports/NX/NXTransport.py:76 transports/TSNX/TSNXTransport.py:81
msgid "Cache size en Mb stored at disk"
msgstr "Cache en taille que Mo stocké à disque"

#: transports/NX/NXTransport.py:84 transports/TSNX/TSNXTransport.py:89
msgid "Memory Cache"
msgstr "Mémoire Cache"

#: transports/NX/NXTransport.py:84 transports/TSNX/TSNXTransport.py:89
msgid "Cache size en Mb keept at memory"
msgstr "Taille en Mb montagne à la mémoire de cache."

#: transports/NX/__init__.py:40 transports/TSNX/__init__.py:40
msgid "NX Protocol"
msgstr "Protocole de NX"

#: transports/NX/__init__.py:46
msgid "UDS Actor connector for NX <b>(requires nomachine packages)</b>"
msgstr "Connecteur UDS acteur pour NX <b>(nécessite nomachine packages)</b>"

#: transports/NX/web.py:74
msgid ""
"In order to use this transport, you need to install first Nomachine Nx "
"Client version 3.5.x"
msgstr ""
"Afin d'utiliser ce transport, vous devez installer le premier Nomachine Nx "
"Client version 3.5.x"

#: transports/NX/web.py:75
msgid "you can obtain it for your platform from"
msgstr "vous pouvez l'obtenir pour votre plate-forme de"

#: transports/NX/web.py:75
msgid "nochamine web site"
msgstr "site web de nochamine"

#: transports/RDP/RDPTransport.py:30
msgid "RDP Transport (direct)"
msgstr "Transport de RDP (direct)"

#: transports/RDP/RDPTransport.py:32
msgid "RDP Transport for direct connection"
msgstr "Transport de RDP pour une connexion directe"

#: transports/RDP/RDPTransport.py:39 transports/RDP/TSRDPTransport.py:43
#: transports/RGS-enterprise/RGSTransport.py:44
#: transports/RGS-enterprise/TRGSTransport.py:49
msgid ""
"If not empty, this domain will be always used as credential (used as DOMAIN"
"\\user)"
msgstr ""
"Si ce n'est vide, ce domaine sera toujours utilisé comme des titres de "
"compétences (utilisé comme domaine\\User)"

#: transports/RDP/RDPTransport.py:40 transports/RDP/TSRDPTransport.py:44
msgid "Allow Smartcards"
msgstr "Permettre aux cartes à puce"

#: transports/RDP/RDPTransport.py:40 transports/RDP/TSRDPTransport.py:44
msgid "If checked, this transport will allow the use of smartcards"
msgstr "Si cochée, ce transport permettra l'utilisation de cartes à puce"

#: transports/RDP/RDPTransport.py:41 transports/RDP/TSRDPTransport.py:45
msgid "Allow Printers"
msgstr "Permettre aux imprimantes"

#: transports/RDP/RDPTransport.py:41 transports/RDP/TSRDPTransport.py:45
msgid "If checked, this transport will allow the use of user printers"
msgstr ""
"Si cochée, ce transport permettra l'utilisation des imprimantes utilisateur"

#: transports/RDP/RDPTransport.py:42 transports/RDP/TSRDPTransport.py:46
msgid "Allow Drives"
msgstr "Permettre aux lecteurs"

#: transports/RDP/RDPTransport.py:42 transports/RDP/TSRDPTransport.py:46
msgid "If checked, this transport will allow the use of user drives"
msgstr ""
"Si cochée, ce transport permettra l'utilisation des lecteurs de l'utilisateur"

#: transports/RDP/RDPTransport.py:43 transports/RDP/TSRDPTransport.py:47
msgid "Allow Serials"
msgstr "Permettre aux publications en série"

#: transports/RDP/RDPTransport.py:43 transports/RDP/TSRDPTransport.py:47
msgid "If checked, this transport will allow the use of user serial ports"
msgstr ""
"Si cochée, ce transport permettra l'utilisation de l'utilisateur ports série"

#: transports/RDP/TSRDPTransport.py:31
msgid "RDP Transport (tunneled)"
msgstr "Transport de RDP (tunnel)"

#: transports/RDP/TSRDPTransport.py:33
msgid "RDP Transport for tunneled connection"
msgstr "Transport de RDP de connexion tunnelée"

#: transports/RDP/TSRDPTransport.py:37
#: transports/RGS-enterprise/TRGSTransport.py:43
#: transports/TSNX/TSNXTransport.py:62
msgid "Tunnel server"
msgstr "Serveur de tunnel"

#: transports/RDP/TSRDPTransport.py:37
#: transports/RGS-enterprise/TRGSTransport.py:43
#: transports/TSNX/TSNXTransport.py:62
msgid ""
"IP or Hostname of tunnel server send to client device (\"public\" ip) and "
"port. (use HOST:PORT format)"
msgstr ""
"IP ou nom d'hôte du serveur de tunnel envoyer à la machine cliente (« public "
"» ip) et port. (utilisez le format de l'hôte : PORT)"

#: transports/RDP/TSRDPTransport.py:38
#: transports/RGS-enterprise/TRGSTransport.py:44
#: transports/TSNX/TSNXTransport.py:63
msgid "Tunnel host check"
msgstr "Tunnel hôte cocher"

#: transports/RDP/TSRDPTransport.py:38
#: transports/RGS-enterprise/TRGSTransport.py:44
#: transports/TSNX/TSNXTransport.py:63
msgid ""
"If not empty, this server will be used to check if service is running before "
"assigning it to user. (use HOST:PORT format)"
msgstr ""
"Si ce n'est vide, ce serveur sera utilisé pour vérifier si le service "
"s'exécute avant assignant à l'utilisateur. (utilisez le format de l'hôte : "
"PORT)"

#: transports/RDP/__init__.py:17
msgid "Remote Desktop Protocol"
msgstr "Protocole Bureau distant"

#: transports/RDP/web.py:83
msgid "In order to use this service, you should first install CoRD."
msgstr "Afin d'utiliser ce service, vous devez d'abord installer cordon."

#: transports/RDP/web.py:84 transports/RGS-enterprise/web.py:82
msgid "You can obtain it from"
msgstr "Vous pouvez l'obtenir de"

#: transports/RDP/web.py:84
msgid "CoRD Website"
msgstr "Site Web du cordon"

#: transports/RGS-enterprise/RGSTransport.py:34
#, fuzzy
msgid "RGS Transport (direct)"
msgstr "Transport de RDP (direct)"

#: transports/RGS-enterprise/RGSTransport.py:36
#, fuzzy
msgid "RGS Transport for direct connection"
msgstr "Transport de RDP pour une connexion directe"

#: transports/RGS-enterprise/RGSTransport.py:45
#: transports/RGS-enterprise/TRGSTransport.py:50
msgid "Image quality"
msgstr "Qualité de l'image"

#: transports/RGS-enterprise/RGSTransport.py:46
#: transports/RGS-enterprise/TRGSTransport.py:51
msgid "Quality of image codec (0-100)"
msgstr "Qualité du codec d'image (0-100)"

#: transports/RGS-enterprise/RGSTransport.py:47
#: transports/RGS-enterprise/TRGSTransport.py:52
msgid "Adjustable Quality"
msgstr "Qualité réglable"

#: transports/RGS-enterprise/RGSTransport.py:48
#: transports/RGS-enterprise/TRGSTransport.py:53
msgid "If checked, the image quality will be adjustable with bandwidth"
msgstr "Si cochée, la qualité de l'image sera réglable avec bande passante"

#: transports/RGS-enterprise/RGSTransport.py:49
#: transports/RGS-enterprise/TRGSTransport.py:54
msgid "Min. Adjustable Quality"
msgstr "Min. qualité réglable"

#: transports/RGS-enterprise/RGSTransport.py:50
#: transports/RGS-enterprise/TRGSTransport.py:55
msgid ""
"The lowest image quality applied to images to maintain the minimum update "
"rate."
msgstr ""
"La qualité de l'image plus bas appliquée aux images afin de maintenir la "
"mise à jour minimum taux."

#: transports/RGS-enterprise/RGSTransport.py:51
#: transports/RGS-enterprise/TRGSTransport.py:56
msgid "Adjustable Frame Rate"
msgstr "Cadence réglable"

#: transports/RGS-enterprise/RGSTransport.py:52
#: transports/RGS-enterprise/TRGSTransport.py:57
msgid "Update rate threshold to begin adjusting image quality"
msgstr ""
"Seuil de vitesse de mise à jour pour commencer à ajuster la qualité de "
"l'image"

#: transports/RGS-enterprise/RGSTransport.py:53
#: transports/RGS-enterprise/TRGSTransport.py:58
msgid "Match Local Resolution"
msgstr "Résolution locale de match"

#: transports/RGS-enterprise/RGSTransport.py:54
#: transports/RGS-enterprise/TRGSTransport.py:59
msgid ""
"Change the Sender's resolution to match the Receiver's resolution when "
"connecting"
msgstr ""
"Modifier la résolution de l'expéditeur pour faire correspondre la résolution "
"du séquestre lors de la connexion"

#: transports/RGS-enterprise/RGSTransport.py:55
#: transports/RGS-enterprise/TRGSTransport.py:60
msgid "Redirect USB"
msgstr "Redirection USB"

#: transports/RGS-enterprise/RGSTransport.py:56
#: transports/RGS-enterprise/TRGSTransport.py:61
msgid "If checked, the USB will be redirected."
msgstr "Si cochée, la clé USB est redirigée."

#: transports/RGS-enterprise/RGSTransport.py:57
#: transports/RGS-enterprise/TRGSTransport.py:62
msgid "Redirect Audio"
msgstr "Redirection Audio"

#: transports/RGS-enterprise/RGSTransport.py:58
#: transports/RGS-enterprise/TRGSTransport.py:63
#, fuzzy
msgid "If checked, the Audio will be redirected."
msgstr ""
"Si coché, les informations d'identification utilisées pour se connecter sera "
"vide"

#: transports/RGS-enterprise/RGSTransport.py:59
#: transports/RGS-enterprise/TRGSTransport.py:64
msgid "Redirect Mic"
msgstr "Redirection Mic"

#: transports/RGS-enterprise/RGSTransport.py:60
#: transports/RGS-enterprise/TRGSTransport.py:65
#, fuzzy
msgid "If checked, the Mic will be redirected."
msgstr ""
"Si coché, les informations d'identification utilisées pour se connecter sera "
"vide"

#: transports/RGS-enterprise/TRGSTransport.py:36
#, fuzzy
msgid "RGS Transport (tunneled)"
msgstr "Transport de RDP (tunnel)"

#: transports/RGS-enterprise/TRGSTransport.py:38
#, fuzzy
msgid "RGS Transport for tunneled connection"
msgstr "Transport de RDP de connexion tunnelée"

#: transports/RGS-enterprise/web.py:81
#, fuzzy
msgid "In order to use this service, you should first install RGS Receiver."
msgstr "Afin d'utiliser ce service, vous devez d'abord installer cordon."

#: transports/RGS-enterprise/web.py:82
#, fuzzy
msgid "HP Website"
msgstr "Site Web du cordon"

#: transports/TSNX/TSNXTransport.py:55
msgid "NX Transport (tunneled)"
msgstr "Transport NX (tunnel)"

#: transports/TSNX/TSNXTransport.py:57
msgid "NX Transport for tunneled connection"
msgstr "Transport NX pour connexion tunnelée"

#: web/errors.py:58
msgid "Unknown error"
msgstr "Erreur inconnue"

#: web/errors.py:59
msgid "Transport not found"
msgstr "Transport introuvable"

#: web/errors.py:60
msgid "Service not found"
msgstr "Service introuvable"

#: web/errors.py:61 xmlrpc/auths/AdminAuth.py:171
msgid "Access denied"
msgstr "Accès refusé"

#: web/errors.py:62
msgid ""
"Invalid service. The service is not available at this moment. Please, try "
"later"
msgstr ""
"Service non valide. Le service n'est pas disponible en ce moment. SVP, "
"essayez plus tard"

#: web/errors.py:63
msgid "Maximum services limit reached. Please, contact administrator"
msgstr ""
"Limite de services maximale atteinte. Veuillez contacter administrateur"

#: web/errors.py:64
msgid "You need to enable cookies to let this application work"
msgstr "Vous devez activer les cookies de laisser cette application"

#: web/errors.py:65
msgid "User service not found"
msgstr "Service utilisateur introuvable"

#: web/errors.py:66
#, fuzzy
msgid "Authenticator not found"
msgstr "Authentificateur"

#: web/errors.py:67 xmlrpc/auths/AdminAuth.py:169
msgid "Invalid authenticator"
msgstr "Authentificateur non valide"

#: web/views.py:334
#, fuzzy
msgid "Authenticator do not provides information"
msgstr "Authentificateur n'existe pas"

#: web/forms/LoginForm.py:59
msgid "Authenticator"
msgstr "Authentificateur"

#: xmlrpc/auths/AdminAuth.py:113
msgid "Credentials no longer valid"
msgstr "Informations d'identification n'est plus valides"

#: xmlrpc/auths/AdminAuth.py:149
msgid "Administration"
msgstr "Administration"

#: xmlrpc/auths/AdminAuth.py:164
msgid "Invalid credentials"
msgstr "Informations d'identification non valides"

#: xmlrpc/auths/Authenticators.py:106
msgid "Authenticator does not exists"
msgstr "Authentificateur n'existe pas"

#: xmlrpc/auths/Authenticators.py:161 xmlrpc/osmanagers/OSManagers.py:115
#: xmlrpc/services/ServiceProviders.py:115
#: xmlrpc/services/ServiceProviders.py:139 xmlrpc/services/Services.py:160
#: xmlrpc/services/Services.py:184 xmlrpc/transports/Networks.py:86
#: xmlrpc/transports/Networks.py:97
#, python-format
msgid "Name %s already exists"
msgstr "Nom %s existe déjà"

#: xmlrpc/auths/Authenticators.py:234
msgid "Authenticator do not supports search"
msgstr "Authenticateur ne soutient la recherche"

#: xmlrpc/auths/Authenticators.py:240
msgid "Specified authenticator do not exists anymore. Please, reload gui"
msgstr "Authentificateur spécifiée n'existe pas plus. Veuillez recharger gui"

#: xmlrpc/auths/Authenticators.py:244
msgid "BUG: Reached a point that should never have been reached!!!"
msgstr "BOGUE : Atteint un point qui devrait jamais été atteint!!!"

#: xmlrpc/osmanagers/OSManagers.py:129
msgid "This os mnager is being used by deployed services"
msgstr ""
"Ce gestionnaire de système d'exploitation est utilisé par les services de "
"déploiements"

#: xmlrpc/osmanagers/OSManagers.py:145
msgid "There is deployed services using this os manager"
msgstr ""
"Il y a des services déployées à l'aide de ce gestionnaire de système "
"d'exploitation"

#: xmlrpc/osmanagers/OSManagers.py:147
msgid "Can't find os manager"
msgstr "Impossible de trouver os gestionnaire"

#: xmlrpc/services/DeployedServices.py:52
msgid "Unknown"
msgstr "Inconnu"

#: xmlrpc/services/DeployedServices.py:112
#: xmlrpc/services/DeployedServices.py:176
#: xmlrpc/services/DeployedServices.py:195
#: xmlrpc/services/DeployedServices.py:211
#: xmlrpc/services/DeployedServices.py:225
#: xmlrpc/services/DeployedServices.py:252
#: xmlrpc/services/DeployedServices.py:266
msgid "Deployed Service does not exists"
msgstr "Service déployée n'existe pas"

#: xmlrpc/services/DeployedServices.py:209
msgid "Group does not exists"
msgstr "Groupe n'existe pas"

#: xmlrpc/services/DeployedServices.py:237
msgid "Can't find deployed service"
msgstr "Impossible de trouver le service déployé"

#: xmlrpc/services/DeployedServices.py:250
msgid "Transport does not exists"
msgstr "Transport n'existe pas"

#: xmlrpc/services/DeployedServices.py:281
msgid "Deployed service does not exists"
msgstr "Service déployée n'existe pas"

#: xmlrpc/services/ServiceProviders.py:154
msgid "Can't delete service provider with services associated"
msgstr ""
"Impossible de supprimer le fournisseur de service avec services associés"

#: xmlrpc/services/ServiceProviders.py:157
msgid "Can't locate the service provider"
msgstr "Impossible de trouver le fournisseur de services"

#: xmlrpc/services/ServiceProviders.py:157 xmlrpc/services/Services.py:202
#: xmlrpc/transports/Networks.py:70 xmlrpc/transports/Networks.py:78
#: xmlrpc/transports/Networks.py:95
msgid "Please, refresh interface"
msgstr "Veuillez actualiser interface"

#: xmlrpc/services/Services.py:199
msgid "Can't delete services with deployed services associated"
msgstr "Impossible de supprimer les services avec des services déployés liés"

#: xmlrpc/services/Services.py:202
msgid "Can't locate the service"
msgstr "Impossible de localiser le service"

#: xmlrpc/services/UserDeployedServices.py:94
#: xmlrpc/services/UserDeployedServices.py:110
msgid "The deployed service is not active"
msgstr "Le service de déploiement n'est pas actif"

#: xmlrpc/services/UserDeployedServices.py:97
#: xmlrpc/services/UserDeployedServices.py:113
msgid "This service don't allows assignations"
msgstr "Ce service ne permet l'assignation"

#: xmlrpc/services/UserDeployedServices.py:102
#: xmlrpc/services/UserDeployedServices.py:120
msgid "Deployed service not found!!! (refresh interface)"
msgstr "Déployées service introuvable!!! (actualisation interface)"

#: xmlrpc/services/UserDeployedServices.py:122
msgid "User not found!!! (refresh interface)"
msgstr "Utilisateur introuvable!!! (actualisation interface)"

#: xmlrpc/services/UserDeployedServices.py:141
msgid "No error"
msgstr "Pas d'erreur"

#: xmlrpc/services/UserDeployedServices.py:147
msgid "User deployed service not found!!!"
msgstr "Service de l'utilisateur ne se trouve pas déployée!!!"

#: xmlrpc/transports/Networks.py:70
msgid "Can't locate the transport"
msgstr "Impossible de localiser le transport"

#: xmlrpc/transports/Networks.py:78 xmlrpc/transports/Networks.py:95
msgid "Can't locate the network"
msgstr "Impossible de localiser le réseau"

#~ msgid "None OS Manager"
#~ msgstr "Aucun gestionnaire de l'OS"

#~ msgid "Os Manager with no actions"
#~ msgstr "Gestionnaire d'os avec aucune action"

#~ msgid "Base Service"
#~ msgstr "Service de base"

#~ msgid "None"
#~ msgstr "Aucun"
